version: '3.3'

services:
    infomap:
        image: mapequation/infomap
        build:
            context: .
            dockerfile: ./docker/infomap.Dockerfile
        volumes:
            - .:/data
        network_mode: none

    notebook:
        image: mapequation/infomap:notebook
        build:
            context: .
            dockerfile: ./docker/notebook.Dockerfile
        ports:
            - 8888:8888
        volumes:
            - .:/me
