# Defaults, option specs, and CLI argument construction.
# Generated by scripts/generate_binding_options.py from ./Infomap --print-json-parameters.
# Edit src/io/Config.cpp or interfaces/parameters/overrides.json, then run
# make build-binding-options.

DEFAULT_META_DATA_RATE <- 1.0
DEFAULT_VERBOSITY_LEVEL <- 1L
DEFAULT_TELEPORTATION_PROB <- 0.15
DEFAULT_MULTILAYER_RELAX_RATE <- 0.15
DEFAULT_SEED <- 123L
DEFAULT_CORE_LOOP_CODELENGTH_THRESHOLD <- 1e-10
DEFAULT_TUNE_ITER_RELATIVE_THRESHOLD <- 1e-5

.skip_when_null <- function(x) !is.null(x)
.skip_when_not_equal <- function(default) function(x) !identical(x, default)

INPUT_OPTIONS <- list(
  list(type = "flag", name = "skip_adjust_bipartite_flow", flag = "--skip-adjust-bipartite-flow", default = FALSE),
  list(type = "flag", name = "bipartite_teleportation", flag = "--bipartite-teleportation", default = FALSE),
  list(type = "value", name = "weight_threshold", flag = "--weight-threshold", default = NULL, include = .skip_when_null),
  list(type = "value", name = "node_limit", flag = "--node-limit", default = NULL, include = .skip_when_null),
  list(type = "value", name = "matchable_multilayer_ids", flag = "--matchable-multilayer-ids", default = NULL, include = .skip_when_null),
  list(type = "value", name = "cluster_data", flag = "--cluster-data", default = NULL, include = .skip_when_null),
  list(type = "flag", name = "assign_to_neighbouring_module", flag = "--assign-to-neighbouring-module", default = FALSE),
  list(type = "value", name = "meta_data", flag = "--meta-data", default = NULL, include = .skip_when_null),
  list(type = "value", name = "meta_data_rate", flag = "--meta-data-rate", default = DEFAULT_META_DATA_RATE, include = .skip_when_not_equal(DEFAULT_META_DATA_RATE)),
  list(type = "flag", name = "meta_data_unweighted", flag = "--meta-data-unweighted", default = FALSE),
  list(type = "flag", name = "no_infomap", flag = "--no-infomap", default = FALSE)
)

OUTPUT_OPTIONS <- list(
  list(type = "value", name = "out_name", flag = "--out-name", default = NULL, include = .skip_when_null),
  list(type = "flag", name = "no_file_output", flag = "--no-file-output", default = FALSE),
  list(type = "flag", name = "tree", flag = "--tree", default = FALSE),
  list(type = "flag", name = "ftree", flag = "--ftree", default = FALSE),
  list(type = "flag", name = "clu", flag = "--clu", default = FALSE),
  list(type = "value", name = "clu_level", flag = "--clu-level", default = NULL, include = .skip_when_null),
  list(type = "flag", name = "hide_bipartite_nodes", flag = "--hide-bipartite-nodes", default = FALSE),
  list(type = "flag", name = "print_all_trials", flag = "--print-all-trials", default = FALSE),
  list(type = "flag", name = "silent", flag = "--silent", default = FALSE)
)

ALGORITHM_OPTIONS <- list(
  list(type = "flag", name = "two_level", flag = "--two-level", default = FALSE),
  list(type = "value", name = "flow_model", flag = "--flow-model", default = NULL, include = .skip_when_null),
  list(type = "flag", name = "recorded_teleportation", flag = "--recorded-teleportation", default = FALSE),
  list(type = "flag", name = "use_node_weights_as_flow", flag = "--use-node-weights-as-flow", default = FALSE),
  list(type = "flag", name = "to_nodes", flag = "--to-nodes", default = FALSE),
  list(type = "value", name = "teleportation_probability", flag = "--teleportation-probability", default = DEFAULT_TELEPORTATION_PROB, include = .skip_when_not_equal(DEFAULT_TELEPORTATION_PROB)),
  list(type = "flag", name = "regularized", flag = "--regularized", default = FALSE),
  list(type = "value", name = "regularization_strength", flag = "--regularization-strength", default = 1.0, include = .skip_when_not_equal(1.0)),
  list(type = "flag", name = "entropy_corrected", flag = "--entropy-corrected", default = FALSE),
  list(type = "value", name = "entropy_correction_strength", flag = "--entropy-correction-strength", default = 1.0, include = .skip_when_not_equal(1.0)),
  list(type = "value", name = "markov_time", flag = "--markov-time", default = 1.0, include = .skip_when_not_equal(1.0)),
  list(type = "flag", name = "variable_markov_time", flag = "--variable-markov-time", default = FALSE),
  list(type = "value", name = "variable_markov_damping", flag = "--variable-markov-damping", default = 1.0, include = .skip_when_not_equal(1.0)),
  list(type = "value", name = "variable_markov_min_scale", flag = "--variable-markov-min-scale", default = 1.0, include = .skip_when_not_equal(1.0)),
  list(type = "value", name = "preferred_number_of_modules", flag = "--preferred-number-of-modules", default = NULL, include = .skip_when_null),
  list(type = "value", name = "multilayer_relax_rate", flag = "--multilayer-relax-rate", default = DEFAULT_MULTILAYER_RELAX_RATE, include = .skip_when_not_equal(DEFAULT_MULTILAYER_RELAX_RATE)),
  list(type = "value", name = "multilayer_relax_limit", flag = "--multilayer-relax-limit", default = NULL, include = .skip_when_null),
  list(type = "value", name = "multilayer_relax_limit_up", flag = "--multilayer-relax-limit-up", default = NULL, include = .skip_when_null),
  list(type = "value", name = "multilayer_relax_limit_down", flag = "--multilayer-relax-limit-down", default = NULL, include = .skip_when_null),
  list(type = "flag", name = "multilayer_relax_by_jsd", flag = "--multilayer-relax-by-jsd", default = FALSE)
)

ACCURACY_OPTIONS <- list(
  list(type = "value", name = "seed", flag = "--seed", default = DEFAULT_SEED, include = .skip_when_not_equal(DEFAULT_SEED)),
  list(type = "value", name = "num_trials", flag = "--num-trials", default = 1L, include = .skip_when_not_equal(1L)),
  list(type = "value", name = "core_loop_limit", flag = "--core-loop-limit", default = 10L, include = .skip_when_not_equal(10L)),
  list(type = "value", name = "core_level_limit", flag = "--core-level-limit", default = NULL, include = .skip_when_null),
  list(type = "value", name = "tune_iteration_limit", flag = "--tune-iteration-limit", default = NULL, include = .skip_when_null),
  list(type = "value", name = "core_loop_codelength_threshold", flag = "--core-loop-codelength-threshold", default = DEFAULT_CORE_LOOP_CODELENGTH_THRESHOLD, include = .skip_when_not_equal(DEFAULT_CORE_LOOP_CODELENGTH_THRESHOLD)),
  list(type = "value", name = "tune_iteration_relative_threshold", flag = "--tune-iteration-relative-threshold", default = DEFAULT_TUNE_ITER_RELATIVE_THRESHOLD, include = .skip_when_not_equal(DEFAULT_TUNE_ITER_RELATIVE_THRESHOLD)),
  list(type = "flag", name = "inner_parallelization", flag = "--inner-parallelization", default = FALSE),
  list(type = "flag", name = "prefer_modular_solution", flag = "--prefer-modular-solution", default = FALSE),
  list(type = "value", name = "num_random_moves", flag = "--num-random-moves", default = NULL, include = .skip_when_null),
  list(type = "value", name = "max_degree_for_random_moves", flag = "--max-degree-for-random-moves", default = NULL, include = .skip_when_null),
  list(type = "flag", name = "solution_landscape_tracking", flag = "--solution-landscape-tracking", default = FALSE),
  list(type = "value", name = "solution_landscape_stop_after", flag = "--solution-landscape-stop-after", default = NULL, include = .skip_when_null)
)

OPTION_FIELD_NAMES <- c(
  "include_self_links", "skip_adjust_bipartite_flow", "bipartite_teleportation", "weight_threshold",
  "no_self_links", "node_limit", "matchable_multilayer_ids", "cluster_data",
  "assign_to_neighbouring_module", "meta_data", "meta_data_rate", "meta_data_unweighted",
  "no_infomap", "out_name", "no_file_output", "tree",
  "ftree", "clu", "clu_level", "output",
  "hide_bipartite_nodes", "print_all_trials", "verbosity_level", "silent",
  "two_level", "flow_model", "directed", "recorded_teleportation",
  "use_node_weights_as_flow", "to_nodes", "teleportation_probability", "regularized",
  "regularization_strength", "entropy_corrected", "entropy_correction_strength", "markov_time",
  "variable_markov_time", "variable_markov_damping", "variable_markov_min_scale", "preferred_number_of_modules",
  "multilayer_relax_rate", "multilayer_relax_limit", "multilayer_relax_limit_up", "multilayer_relax_limit_down",
  "multilayer_relax_by_jsd", "seed", "num_trials", "core_loop_limit",
  "core_level_limit", "tune_iteration_limit", "core_loop_codelength_threshold", "tune_iteration_relative_threshold",
  "fast_hierarchical_solution", "inner_parallelization", "prefer_modular_solution", "num_random_moves",
  "max_degree_for_random_moves", "solution_landscape_tracking", "solution_landscape_stop_after"
)

OPTION_DEFAULTS <- list(
  include_self_links = NULL,
  skip_adjust_bipartite_flow = FALSE,
  bipartite_teleportation = FALSE,
  weight_threshold = NULL,
  no_self_links = FALSE,
  node_limit = NULL,
  matchable_multilayer_ids = NULL,
  cluster_data = NULL,
  assign_to_neighbouring_module = FALSE,
  meta_data = NULL,
  meta_data_rate = DEFAULT_META_DATA_RATE,
  meta_data_unweighted = FALSE,
  no_infomap = FALSE,
  out_name = NULL,
  no_file_output = FALSE,
  tree = FALSE,
  ftree = FALSE,
  clu = FALSE,
  clu_level = NULL,
  output = NULL,
  hide_bipartite_nodes = FALSE,
  print_all_trials = FALSE,
  verbosity_level = DEFAULT_VERBOSITY_LEVEL,
  silent = FALSE,
  two_level = FALSE,
  flow_model = NULL,
  directed = NULL,
  recorded_teleportation = FALSE,
  use_node_weights_as_flow = FALSE,
  to_nodes = FALSE,
  teleportation_probability = DEFAULT_TELEPORTATION_PROB,
  regularized = FALSE,
  regularization_strength = 1.0,
  entropy_corrected = FALSE,
  entropy_correction_strength = 1.0,
  markov_time = 1.0,
  variable_markov_time = FALSE,
  variable_markov_damping = 1.0,
  variable_markov_min_scale = 1.0,
  preferred_number_of_modules = NULL,
  multilayer_relax_rate = DEFAULT_MULTILAYER_RELAX_RATE,
  multilayer_relax_limit = NULL,
  multilayer_relax_limit_up = NULL,
  multilayer_relax_limit_down = NULL,
  multilayer_relax_by_jsd = FALSE,
  seed = DEFAULT_SEED,
  num_trials = 1L,
  core_loop_limit = 10L,
  core_level_limit = NULL,
  tune_iteration_limit = NULL,
  core_loop_codelength_threshold = DEFAULT_CORE_LOOP_CODELENGTH_THRESHOLD,
  tune_iteration_relative_threshold = DEFAULT_TUNE_ITER_RELATIVE_THRESHOLD,
  fast_hierarchical_solution = NULL,
  inner_parallelization = FALSE,
  prefer_modular_solution = FALSE,
  num_random_moves = NULL,
  max_degree_for_random_moves = NULL,
  solution_landscape_tracking = FALSE,
  solution_landscape_stop_after = NULL
)

#' Build a reusable Infomap options list
#'
#' Returns a named list with one entry per Infomap CLI option. All
#' arguments default to the Infomap-internal defaults, so callers only
#' need to supply the options they want to override. The returned list
#' is accepted by [Infomap()] and `Infomap$run()`.
#'
#' Argument names mirror the Infomap CLI flags (with hyphens replaced by
#' underscores) and the keyword arguments accepted by the Python interface.
#'
#' @param ... Named option overrides. See **Options** below.
#'
#' @section Options:
#' Input
#' \describe{
#'   \item{`include_self_links`}{Deprecated. Self-links are included by default; use `no_self_links = TRUE` to exclude them.}
#'   \item{`skip_adjust_bipartite_flow`}{Skip distributing all flow from the bipartite nodes to the primary nodes.}
#'   \item{`bipartite_teleportation`}{Teleport like the bipartite flow instead of two-step (unipartite) teleportation.}
#'   \item{`weight_threshold`}{Limit the number of links to read from the network. Ignore links with less weight than the threshold.}
#'   \item{`no_self_links`}{Exclude self links in the input network.}
#'   \item{`node_limit`}{Limit the number of nodes to read from the network. Ignore links connected to ignored nodes.}
#'   \item{`matchable_multilayer_ids`}{Construct state ids from node and layer ids that are consistent across networks for the same max number of layers. Set to at least the largest layer id among networks to match.}
#'   \item{`cluster_data`}{Provide an initial two-level (clu format) or multi-layer (tree format) solution.}
#'   \item{`assign_to_neighbouring_module`}{Assign nodes without module assignments (from --cluster-data) to the module assignment of a neighbouring node if possible.}
#'   \item{`meta_data`}{Provide meta data (clu format) that should be encoded.}
#'   \item{`meta_data_rate`}{Metadata encoding rate. Default is to encode each step.}
#'   \item{`meta_data_unweighted`}{Don't weight meta data by node flow.}
#'   \item{`no_infomap`}{Don't run the optimizer. Useful to calculate codelength of provided cluster data or to print non-modular statistics.}
#' }
#'
#' Output
#' \describe{
#'   \item{`out_name`}{Name for the output files, e.g. \[output_directory\]/\[out-name\].tree}
#'   \item{`no_file_output`}{Don't write output to file.}
#'   \item{`tree`}{Write a tree file with the modular hierarchy. Automatically enabled if no other output is specified.}
#'   \item{`ftree`}{Write a ftree file with the modular hierarchy including aggregated links between (nested) modules. (Used by Network Navigator)}
#'   \item{`clu`}{Write a clu file with the top cluster ids for each node.}
#'   \item{`clu_level`}{For clu output, print modules at specified depth from root. Use -1 for bottom level modules.}
#'   \item{`output`}{Comma-separated output formats without spaces, e.g. -o clu,tree,ftree. Options: clu, tree, ftree, newick, json, csv, network, states, flow.}
#'   \item{`hide_bipartite_nodes`}{Project bipartite solution to unipartite.}
#'   \item{`print_all_trials`}{Print all trials to separate files.}
#'   \item{`verbosity_level`}{Verbose output on the console. Add additional 'v' flags to increase verbosity up to -vvv.}
#'   \item{`silent`}{No output on the console.}
#' }
#'
#' Algorithm
#' \describe{
#'   \item{`two_level`}{Optimize a two-level partition of the network. Default is multi-level.}
#'   \item{`flow_model`}{Specify flow model. Options: undirected, directed, undirdir, outdirdir, rawdir, precomputed.}
#'   \item{`directed`}{Assume directed links. Shorthand for '--flow-model directed'.}
#'   \item{`recorded_teleportation`}{If teleportation is used to calculate the flow, also record it when minimizing codelength.}
#'   \item{`use_node_weights_as_flow`}{Use node weights (from api or after names in Pajek format) as flow, normalized to sum to 1}
#'   \item{`to_nodes`}{Teleport to nodes instead of to links, assuming uniform node weights if no such input data.}
#'   \item{`teleportation_probability`}{Probability of teleporting to a random node or link.}
#'   \item{`regularized`}{Effectively add a fully connected Bayesian prior network to not overfit due to missing links. Implies recorded teleportation}
#'   \item{`regularization_strength`}{Adjust relative strength of Bayesian prior network with this multiplier.}
#'   \item{`entropy_corrected`}{Correct for negative entropy bias in small samples (many modules).}
#'   \item{`entropy_correction_strength`}{Increase or decrease the default entropy correction with this factor.}
#'   \item{`markov_time`}{Scale link flow to change the cost of moving between modules. Higher values results in fewer modules.}
#'   \item{`variable_markov_time`}{Increase Markov time locally to level out link flow. Reduces risk of overpartitioning sparse areas while keeping high resolution in dense areas.}
#'   \item{`variable_markov_damping`}{Damping parameter for variable Markov time, to scale with local effective degree (0) or local entropy (1).}
#'   \item{`variable_markov_min_scale`}{Minimum local scale for nodes with zero entropy to avoid division by zero. Local Markov time is max scale divided by local scale.}
#'   \item{`preferred_number_of_modules`}{Penalize solutions the more they differ from this number.}
#'   \item{`multilayer_relax_rate`}{Probability to relax the constraint to move only in the current layer.}
#'   \item{`multilayer_relax_limit`}{Number of neighboring layers in each direction to relax to. If negative, relax to any layer.}
#'   \item{`multilayer_relax_limit_up`}{Number of neighboring layers with higher id to relax to. If negative, relax to any layer.}
#'   \item{`multilayer_relax_limit_down`}{Number of neighboring layers with lower id to relax to. If negative, relax to any layer.}
#'   \item{`multilayer_relax_by_jsd`}{Relax proportional to the out-link similarity measured by the Jensen-Shannon divergence.}
#' }
#'
#' Accuracy
#' \describe{
#'   \item{`seed`}{A seed (integer) to the random number generator for reproducible results.}
#'   \item{`num_trials`}{Number of outer-most loops to run before picking the best solution.}
#'   \item{`core_loop_limit`}{Limit the number of loops that tries to move each node into the best possible module.}
#'   \item{`core_level_limit`}{Limit the number of times the core loops are reapplied on existing modular network to search bigger structures.}
#'   \item{`tune_iteration_limit`}{Limit the number of main iterations in the two-level partition algorithm. 0 means no limit.}
#'   \item{`core_loop_codelength_threshold`}{Minimum codelength threshold for accepting a new solution in core loop.}
#'   \item{`tune_iteration_relative_threshold`}{Set codelength improvement threshold of each new tune iteration to 'f' times the initial two-level codelength.}
#'   \item{`fast_hierarchical_solution`}{Find top modules fast. Use -FF to keep all fast levels. Use -FFF to skip recursive part.}
#'   \item{`inner_parallelization`}{Parallelize the inner-most loop for greater speed. This may give some accuracy tradeoff.}
#'   \item{`prefer_modular_solution`}{Prefer modular solutions even if they are worse than putting all nodes in one module.}
#'   \item{`num_random_moves`}{Number of random moves to try in core loop to try merge weakly connected nodes.}
#'   \item{`max_degree_for_random_moves`}{Maximum degree of nodes for which to try random moves.}
#'   \item{`solution_landscape_tracking`}{Experimentally track final solution fingerprints across trials.}
#'   \item{`solution_landscape_stop_after`}{Stop early after this many consecutive trials revisit known solution-landscape solutions. Requires --solution-landscape-tracking.}
#' }
#'
#' @return A named list of options.
#' @examples
#' opts <- infomap_options(num_trials = 10, two_level = TRUE)
#' im <- Infomap(opts = opts, silent = TRUE)
#' @export
infomap_options <- function(...) {
  overrides <- list(...)
  unknown <- setdiff(names(overrides), OPTION_FIELD_NAMES)
  if (length(unknown) > 0L) {
    stop(
      "Unknown infomap options: ", paste(unknown, collapse = ", "),
      ". See ?infomap_options for the full list.",
      call. = FALSE
    )
  }
  opts <- OPTION_DEFAULTS
  for (name in names(overrides)) {
    opts[[name]] <- overrides[[name]]
  }
  opts
}

.append_specs <- function(parts, opts, specs) {
  for (spec in specs) {
    value <- opts[[spec$name]]
    if (identical(spec$type, "flag")) {
      if (isTRUE(value)) parts <- c(parts, spec$flag)
      next
    }
    include <- if (is.null(spec$include)) function(v) !is.null(v) && !identical(v, spec$default) else spec$include
    if (isTRUE(include(value))) {
      parts <- c(parts, paste(spec$flag, format_value(value)))
    }
  }
  parts
}

format_value <- function(value) {
  if (is.character(value)) return(value)
  if (is.logical(value)) return(if (isTRUE(value)) "true" else "false")
  if (is.numeric(value)) {
    if (is.integer(value) || (is.finite(value) && value == as.integer(value))) {
      return(format(as.integer(value), scientific = FALSE))
    }
    return(format(value, scientific = FALSE, trim = TRUE))
  }
  as.character(value)
}

#' Render an Infomap options list to a CLI argument string
#'
#' This is exported for advanced use; most callers should pass options
#' directly to [Infomap()] or `Infomap$run()`.
#'
#' @param args Optional raw argument string to prepend.
#' @param opts Options list from [infomap_options()] (or `NULL`).
#'
#' @return A single character string of CLI arguments.
#' @export
construct_args <- function(args = NULL, opts = NULL) {
  if (is.null(opts)) opts <- OPTION_DEFAULTS
  parts <- character(0)

  if (!is.null(opts$include_self_links)) {
    .Deprecated(
      new = "no_self_links",
      package = "infomap",
      old = "include_self_links",
      msg = "include_self_links is deprecated; use no_self_links = TRUE to exclude self-links."
    )
  }

  parts <- .append_specs(parts, opts, INPUT_OPTIONS)

  if ((!is.null(opts$include_self_links) && !isTRUE(opts$include_self_links)) ||
      isTRUE(opts$no_self_links)) {
    parts <- c(parts, "--no-self-links")
  }

  parts <- .append_specs(parts, opts, OUTPUT_OPTIONS)

  if (isTRUE(opts$verbosity_level > 1L)) {
    parts <- c(parts, paste0("-", strrep("v", opts$verbosity_level)))
  }

  if (!is.null(opts$output)) {
    parts <- c(parts, paste("--output", paste(opts$output, collapse = ",")))
  }
  parts <- .append_specs(parts, opts, ALGORITHM_OPTIONS)

  if (!is.null(opts$directed)) {
    parts <- c(parts, if (isTRUE(opts$directed)) "--directed" else "--flow-model undirected")
  }
  parts <- .append_specs(parts, opts, ACCURACY_OPTIONS)

  if (!is.null(opts$fast_hierarchical_solution)) {
    parts <- c(parts, paste0("-", strrep("F", opts$fast_hierarchical_solution)))
  }

  rendered <- paste(parts, collapse = " ")
  if (is.null(args) || !nzchar(args)) {
    rendered
  } else if (length(parts) == 0L) {
    args
  } else {
    paste(args, rendered)
  }
}
