# Defaults, option specs, and CLI argument construction.
# Generated by scripts/generate_binding_options.py from ./Infomap --print-json-parameters.
# Edit src/io/ParameterCatalog.cpp or interfaces/parameters/overrides.json, then run
# make build-binding-options.

.skip_when_null <- function(x) !is.null(x)
.skip_when_not_equal <- function(default) function(x) !identical(x, default)

INPUT_OPTIONS <- list(
  list(type = "flag", name = "skip_adjust_bipartite_flow", flag = "--skip-adjust-bipartite-flow", default = FALSE),
  list(type = "flag", name = "bipartite_teleportation", flag = "--bipartite-teleportation", default = FALSE),
  list(type = "value", name = "weight_threshold", flag = "--weight-threshold", default = NULL, include = .skip_when_null),
  list(type = "value", name = "node_limit", flag = "--node-limit", default = NULL, include = .skip_when_null),
  list(type = "flag", name = "multilayer_self_inter_links", flag = "--multilayer-self-inter-links", default = FALSE),
  list(type = "value", name = "matchable_multilayer_ids", flag = "--matchable-multilayer-ids", default = NULL, include = .skip_when_null),
  list(type = "value", name = "cluster_data", flag = "--cluster-data", default = NULL, include = .skip_when_null),
  list(type = "flag", name = "assign_to_neighbouring_module", flag = "--assign-to-neighbouring-module", default = FALSE),
  list(type = "value", name = "meta_data", flag = "--meta-data", default = NULL, include = .skip_when_null),
  list(type = "value", name = "meta_data_rate", flag = "--meta-data-rate", default = 1.0, include = .skip_when_not_equal(1.0)),
  list(type = "flag", name = "meta_data_unweighted", flag = "--meta-data-unweighted", default = FALSE),
  list(type = "flag", name = "no_infomap", flag = "--no-infomap", default = FALSE),
  list(type = "flag", name = "hard_partition", flag = "--hard-partition", default = FALSE)
)

OUTPUT_OPTIONS <- list(
  list(type = "value", name = "out_name", flag = "--out-name", default = NULL, include = .skip_when_null),
  list(type = "flag", name = "no_file_output", flag = "--no-file-output", default = FALSE),
  list(type = "flag", name = "tree", flag = "--tree", default = FALSE),
  list(type = "flag", name = "ftree", flag = "--ftree", default = FALSE),
  list(type = "flag", name = "clu", flag = "--clu", default = FALSE),
  list(type = "value", name = "clu_level", flag = "--clu-level", default = NULL, include = .skip_when_null),
  list(type = "flag", name = "hide_bipartite_nodes", flag = "--hide-bipartite-nodes", default = FALSE),
  list(type = "flag", name = "print_all_trials", flag = "--print-all-trials", default = FALSE),
  list(type = "flag", name = "silent", flag = "--silent", default = FALSE),
  list(type = "flag", name = "pretty", flag = "--pretty", default = FALSE)
)

ALGORITHM_OPTIONS <- list(
  list(type = "flag", name = "two_level", flag = "--two-level", default = FALSE),
  list(type = "value", name = "flow_model", flag = "--flow-model", default = NULL, include = .skip_when_null),
  list(type = "flag", name = "recorded_teleportation", flag = "--recorded-teleportation", default = FALSE),
  list(type = "flag", name = "use_node_weights_as_flow", flag = "--use-node-weights-as-flow", default = FALSE),
  list(type = "flag", name = "to_nodes", flag = "--to-nodes", default = FALSE),
  list(type = "value", name = "teleportation_probability", flag = "--teleportation-probability", default = 0.15, include = .skip_when_not_equal(0.15)),
  list(type = "value", name = "random_node_check_rate", flag = "--random-node-check-rate", default = NULL, include = .skip_when_null),
  list(type = "flag", name = "regularized", flag = "--regularized", default = FALSE),
  list(type = "value", name = "regularization_strength", flag = "--regularization-strength", default = 1.0, include = .skip_when_not_equal(1.0)),
  list(type = "flag", name = "entropy_corrected", flag = "--entropy-corrected", default = FALSE),
  list(type = "value", name = "entropy_correction_strength", flag = "--entropy-correction-strength", default = 1.0, include = .skip_when_not_equal(1.0)),
  list(type = "value", name = "markov_time", flag = "--markov-time", default = 1.0, include = .skip_when_not_equal(1.0)),
  list(type = "flag", name = "variable_markov_time", flag = "--variable-markov-time", default = FALSE),
  list(type = "value", name = "variable_markov_damping", flag = "--variable-markov-damping", default = 1.0, include = .skip_when_not_equal(1.0)),
  list(type = "value", name = "variable_markov_min_scale", flag = "--variable-markov-min-scale", default = 1.0, include = .skip_when_not_equal(1.0)),
  list(type = "value", name = "preferred_number_of_modules", flag = "--preferred-number-of-modules", default = NULL, include = .skip_when_null),
  list(type = "value", name = "multilayer_relax_rate", flag = "--multilayer-relax-rate", default = 0.15, include = .skip_when_not_equal(0.15)),
  list(type = "value", name = "multilayer_relax_limit", flag = "--multilayer-relax-limit", default = NULL, include = .skip_when_null),
  list(type = "value", name = "multilayer_relax_limit_up", flag = "--multilayer-relax-limit-up", default = NULL, include = .skip_when_null),
  list(type = "value", name = "multilayer_relax_limit_down", flag = "--multilayer-relax-limit-down", default = NULL, include = .skip_when_null),
  list(type = "flag", name = "multilayer_relax_by_jsd", flag = "--multilayer-relax-by-jsd", default = FALSE),
  list(type = "value", name = "multilayer_test", flag = "--multilayer-test", default = NULL, include = .skip_when_null),
  list(type = "flag", name = "multilayer_aggregation", flag = "--multilayer-aggregation", default = FALSE)
)

ACCURACY_OPTIONS <- list(
  list(type = "value", name = "seed", flag = "--seed", default = 123L, include = .skip_when_not_equal(123L)),
  list(type = "value", name = "num_trials", flag = "--num-trials", default = 1L, include = .skip_when_not_equal(1L)),
  list(type = "value", name = "core_loop_limit", flag = "--core-loop-limit", default = 10L, include = .skip_when_not_equal(10L)),
  list(type = "value", name = "core_level_limit", flag = "--core-level-limit", default = NULL, include = .skip_when_null),
  list(type = "value", name = "tune_iteration_limit", flag = "--tune-iteration-limit", default = NULL, include = .skip_when_null),
  list(type = "value", name = "core_loop_codelength_threshold", flag = "--core-loop-codelength-threshold", default = 1e-10, include = .skip_when_not_equal(1e-10)),
  list(type = "value", name = "tune_iteration_relative_threshold", flag = "--tune-iteration-relative-threshold", default = 1e-05, include = .skip_when_not_equal(1e-05)),
  list(type = "flag", name = "inner_parallelization", flag = "--inner-parallelization", default = FALSE),
  list(type = "flag", name = "prefer_modular_solution", flag = "--prefer-modular-solution", default = FALSE),
  list(type = "value", name = "num_random_moves", flag = "--num-random-moves", default = NULL, include = .skip_when_null),
  list(type = "value", name = "max_degree_for_random_moves", flag = "--max-degree-for-random-moves", default = NULL, include = .skip_when_null)
)

OPTION_FIELD_NAMES <- c(
  "include_self_links", "skip_adjust_bipartite_flow", "bipartite_teleportation", "weight_threshold",
  "no_self_links", "node_limit", "multilayer_self_inter_links", "matchable_multilayer_ids",
  "cluster_data", "assign_to_neighbouring_module", "meta_data", "meta_data_rate",
  "meta_data_unweighted", "no_infomap", "hard_partition", "out_name",
  "no_file_output", "tree", "ftree", "clu",
  "clu_level", "output", "hide_bipartite_nodes", "print_all_trials",
  "verbosity_level", "silent", "pretty", "two_level",
  "flow_model", "directed", "recorded_teleportation", "use_node_weights_as_flow",
  "to_nodes", "teleportation_probability", "random_node_check_rate", "regularized",
  "regularization_strength", "entropy_corrected", "entropy_correction_strength", "markov_time",
  "variable_markov_time", "variable_markov_damping", "variable_markov_min_scale", "preferred_number_of_modules",
  "multilayer_relax_rate", "multilayer_relax_limit", "multilayer_relax_limit_up", "multilayer_relax_limit_down",
  "multilayer_relax_by_jsd", "multilayer_test", "multilayer_aggregation", "seed",
  "num_trials", "core_loop_limit", "core_level_limit", "tune_iteration_limit",
  "core_loop_codelength_threshold", "tune_iteration_relative_threshold", "fast_hierarchical_solution", "inner_parallelization",
  "prefer_modular_solution", "num_random_moves", "max_degree_for_random_moves"
)

OPTION_DEFAULTS <- list(
  include_self_links = NULL,
  skip_adjust_bipartite_flow = FALSE,
  bipartite_teleportation = FALSE,
  weight_threshold = NULL,
  no_self_links = FALSE,
  node_limit = NULL,
  multilayer_self_inter_links = FALSE,
  matchable_multilayer_ids = NULL,
  cluster_data = NULL,
  assign_to_neighbouring_module = FALSE,
  meta_data = NULL,
  meta_data_rate = 1.0,
  meta_data_unweighted = FALSE,
  no_infomap = FALSE,
  hard_partition = FALSE,
  out_name = NULL,
  no_file_output = FALSE,
  tree = FALSE,
  ftree = FALSE,
  clu = FALSE,
  clu_level = NULL,
  output = NULL,
  hide_bipartite_nodes = FALSE,
  print_all_trials = FALSE,
  verbosity_level = 1L,
  silent = FALSE,
  pretty = FALSE,
  two_level = FALSE,
  flow_model = NULL,
  directed = NULL,
  recorded_teleportation = FALSE,
  use_node_weights_as_flow = FALSE,
  to_nodes = FALSE,
  teleportation_probability = 0.15,
  random_node_check_rate = NULL,
  regularized = FALSE,
  regularization_strength = 1.0,
  entropy_corrected = FALSE,
  entropy_correction_strength = 1.0,
  markov_time = 1.0,
  variable_markov_time = FALSE,
  variable_markov_damping = 1.0,
  variable_markov_min_scale = 1.0,
  preferred_number_of_modules = NULL,
  multilayer_relax_rate = 0.15,
  multilayer_relax_limit = NULL,
  multilayer_relax_limit_up = NULL,
  multilayer_relax_limit_down = NULL,
  multilayer_relax_by_jsd = FALSE,
  multilayer_test = NULL,
  multilayer_aggregation = FALSE,
  seed = 123L,
  num_trials = 1L,
  core_loop_limit = 10L,
  core_level_limit = NULL,
  tune_iteration_limit = NULL,
  core_loop_codelength_threshold = 1e-10,
  tune_iteration_relative_threshold = 1e-05,
  fast_hierarchical_solution = NULL,
  inner_parallelization = FALSE,
  prefer_modular_solution = FALSE,
  num_random_moves = NULL,
  max_degree_for_random_moves = NULL
)

#' Build a reusable Infomap options list
#'
#' Returns a named list with one entry per Infomap CLI option. All
#' arguments default to the Infomap-internal defaults, so callers only
#' need to supply the options they want to override. The returned list
#' is accepted by [Infomap()] and `Infomap$run()`.
#'
#' Argument names mirror the Infomap CLI flags (with hyphens replaced by
#' underscores) and the keyword arguments accepted by the Python interface.
#'
#' @param ... Named option overrides. See **Options** below.
#'
#' @section Options:
#' Input
#' \describe{
#'   \item{`include_self_links`}{Deprecated. Self-links are included by default; use `no_self_links = TRUE` to exclude them.}
#'   \item{`skip_adjust_bipartite_flow`}{Keep flow on bipartite nodes instead of distributing it to primary nodes.}
#'   \item{`bipartite_teleportation`}{Use bipartite teleportation instead of the default two-step unipartite teleportation.}
#'   \item{`weight_threshold`}{Ignore input links with weight below this threshold.}
#'   \item{`no_self_links`}{Exclude self-links from the input network.}
#'   \item{`node_limit`}{Read only nodes up to this node id and ignore links connected to higher node ids.}
#'   \item{`multilayer_self_inter_links`}{For inter/intra format, restrict inter-layer links within same physical node but adjust flow to approximate physical steps}
#'   \item{`matchable_multilayer_ids`}{Construct state ids from node ids and layer ids that stay comparable across networks. Set at least to the largest layer id among networks to match.}
#'   \item{`cluster_data`}{Read an initial partition from a clu file or a hierarchy from a tree/ftree file. Tree input may use physical or state nodes for higher-order networks.}
#'   \item{`assign_to_neighbouring_module`}{With --cluster-data, assign nodes missing module ids to a neighboring node's module when possible.}
#'   \item{`meta_data`}{Read metadata to encode from a clu-format file.}
#'   \item{`meta_data_rate`}{With --meta-data, set the metadata encoding rate. The default encodes metadata at each step.}
#'   \item{`meta_data_unweighted`}{With --meta-data, encode metadata without weighting by node flow.}
#'   \item{`no_infomap`}{Skip optimization. Use this to calculate codelength for --cluster-data or to print non-modular statistics.}
#'   \item{`hard_partition`}{Do not split initial partition.}
#' }
#'
#' Output
#' \describe{
#'   \item{`out_name`}{Base name for output files, for example \[out_directory\]/\[out-name\].tree.}
#'   \item{`no_file_output`}{Do not write output files.}
#'   \item{`tree`}{Write the modular hierarchy to a tree file. Enabled by default when no other output format is selected.}
#'   \item{`ftree`}{Write the modular hierarchy and aggregated links between nested modules to an ftree file. Used by Network Navigator.}
#'   \item{`clu`}{Write top-level module ids for each node to a clu file.}
#'   \item{`clu_level`}{With --clu or --output clu, write module ids at this depth from the root. Use -1 for bottom-level modules.}
#'   \item{`output`}{Write selected output formats as a comma-separated list without spaces, e.g. -o clu,tree,ftree. Options: clu, tree, ftree, newick, json, csv, network, states, flow.}
#'   \item{`hide_bipartite_nodes`}{Hide bipartite nodes in output by projecting the solution to primary nodes.}
#'   \item{`print_all_trials`}{Write each trial to separate output files. Has effect only when --num-trials is greater than 1.}
#'   \item{`verbosity_level`}{Increase console verbosity. Add more v flags to increase verbosity up to -vvv.}
#'   \item{`silent`}{Suppress console output.}
#'   \item{`pretty`}{Use modernized console output with color and Unicode on interactive terminals.}
#' }
#'
#' Algorithm
#' \describe{
#'   \item{`two_level`}{Optimize a two-level partition instead of the default multi-level hierarchy.}
#'   \item{`flow_model`}{Choose how Infomap derives flow from the input links. Options: undirected, directed, undirdir, outdirdir, rawdir, precomputed.}
#'   \item{`directed`}{Treat input links as directed. Shorthand for --flow-model directed.}
#'   \item{`recorded_teleportation`}{When teleportation is used to calculate flow, also record teleportation steps in the codelength.}
#'   \item{`use_node_weights_as_flow`}{Use node weights from the API or Pajek node records as normalized node flow.}
#'   \item{`to_nodes`}{Teleport to nodes instead of links. Uses uniform node weights unless node weights are provided.}
#'   \item{`teleportation_probability`}{Set the probability of teleporting to a random node or link when calculating flow.}
#'   \item{`random_node_check_rate`}{Check a selected proportion of nodes for moves if recorded teleportation}
#'   \item{`regularized`}{Add a fully connected Bayesian prior network to reduce overfitting to missing links. Activates --recorded-teleportation.}
#'   \item{`regularization_strength`}{Scale the relative strength of the Bayesian prior network used by --regularized.}
#'   \item{`entropy_corrected`}{Correct for negative entropy bias in small samples, especially solutions with many modules.}
#'   \item{`entropy_correction_strength`}{Scale the default correction used by --entropy-corrected.}
#'   \item{`markov_time`}{Scale link flow to change the cost of moving between modules. Higher values result in fewer modules.}
#'   \item{`variable_markov_time`}{Vary Markov time locally to reduce overpartitioning in sparse areas while keeping higher resolution in dense areas.}
#'   \item{`variable_markov_damping`}{With --variable-markov-time, set damping between local effective degree (0) and local entropy (1).}
#'   \item{`variable_markov_min_scale`}{With --variable-markov-time, set the minimum local scale for zero-entropy nodes. Local Markov time is max scale divided by local scale.}
#'   \item{`preferred_number_of_modules`}{Penalize solutions by how far their number of modules differs from this value.}
#'   \item{`multilayer_relax_rate`}{Set the probability of relaxing from a state node to neighboring layers instead of staying in the current layer.}
#'   \item{`multilayer_relax_limit`}{Limit relaxation to this many neighboring layer ids in each direction. Use a negative value to allow relaxation to any layer.}
#'   \item{`multilayer_relax_limit_up`}{Limit relaxation upward to this many higher neighboring layer ids. Use a negative value to allow relaxation to any higher layer.}
#'   \item{`multilayer_relax_limit_down`}{Limit relaxation downward to this many lower neighboring layer ids. Use a negative value to allow relaxation to any lower layer.}
#'   \item{`multilayer_relax_by_jsd`}{Weight multilayer relaxation by out-link similarity measured with Jensen-Shannon divergence.}
#'   \item{`multilayer_test`}{Testing different multilayer implementations.}
#'   \item{`multilayer_aggregation`}{Experimental: Use aggregated multilayer network.}
#' }
#'
#' Accuracy
#' \describe{
#'   \item{`seed`}{Set the random number generator seed for reproducible results.}
#'   \item{`num_trials`}{Run this many independent trials and keep the best solution.}
#'   \item{`core_loop_limit`}{Limit how many core loops try to move each node to the best module.}
#'   \item{`core_level_limit`}{Limit how many times core loops are reapplied to the aggregated modular network to find larger structures. 0 means no limit.}
#'   \item{`tune_iteration_limit`}{Limit the main iterations in the two-level partition algorithm. 0 means no limit.}
#'   \item{`core_loop_codelength_threshold`}{Require at least this codelength improvement to accept a new solution in a core loop.}
#'   \item{`tune_iteration_relative_threshold`}{Require each tune iteration to improve codelength by this fraction of the initial two-level codelength.}
#'   \item{`fast_hierarchical_solution`}{Find top modules quickly. Use -FF to keep all fast levels. Use -FFF to skip recursive refinement.}
#'   \item{`inner_parallelization`}{Parallelize the innermost loop for speed, with a possible accuracy tradeoff.}
#'   \item{`prefer_modular_solution`}{Prefer a modular solution even when one module gives a lower codelength.}
#'   \item{`num_random_moves`}{Try this many random moves in each core loop to merge weakly connected nodes.}
#'   \item{`max_degree_for_random_moves`}{Try random moves only for nodes with degree at most this value.}
#' }
#'
#' @return A named list of options.
#' @examples
#' opts <- infomap_options(num_trials = 10, two_level = TRUE)
#' im <- Infomap(opts = opts, silent = TRUE)
#' @export
infomap_options <- function(...) {
  overrides <- list(...)
  unknown <- setdiff(names(overrides), OPTION_FIELD_NAMES)
  if (length(unknown) > 0L) {
    stop(
      "Unknown infomap options: ", paste(unknown, collapse = ", "),
      ". See ?infomap_options for the full list.",
      call. = FALSE
    )
  }
  opts <- OPTION_DEFAULTS
  for (name in names(overrides)) {
    opts[[name]] <- overrides[[name]]
  }
  opts
}

.append_specs <- function(parts, opts, specs) {
  for (spec in specs) {
    value <- opts[[spec$name]]
    if (identical(spec$type, "flag")) {
      if (isTRUE(value)) parts <- c(parts, spec$flag)
      next
    }
    include <- if (is.null(spec$include)) function(v) !is.null(v) && !identical(v, spec$default) else spec$include
    if (isTRUE(include(value))) {
      parts <- c(parts, paste(spec$flag, format_value(value)))
    }
  }
  parts
}

format_value <- function(value) {
  if (is.character(value)) return(value)
  if (is.logical(value)) return(if (isTRUE(value)) "true" else "false")
  if (is.numeric(value)) {
    if (is.integer(value) || (is.finite(value) && value == as.integer(value))) {
      return(format(as.integer(value), scientific = FALSE))
    }
    return(format(value, scientific = FALSE, trim = TRUE))
  }
  as.character(value)
}

#' Render an Infomap options list to a CLI argument string
#'
#' This is exported for advanced use; most callers should pass options
#' directly to [Infomap()] or `Infomap$run()`.
#'
#' @param args Optional raw argument string to prepend.
#' @param opts Options list from [infomap_options()] (or `NULL`).
#'
#' @return A single character string of CLI arguments.
#' @export
construct_args <- function(args = NULL, opts = NULL) {
  if (is.null(opts)) opts <- OPTION_DEFAULTS
  parts <- character(0)

  if (!is.null(opts$include_self_links)) {
    .Deprecated(
      new = "no_self_links",
      package = "infomap",
      old = "include_self_links",
      msg = "include_self_links is deprecated; use no_self_links = TRUE to exclude self-links."
    )
  }

  parts <- .append_specs(parts, opts, INPUT_OPTIONS)

  if ((!is.null(opts$include_self_links) && !isTRUE(opts$include_self_links)) ||
      isTRUE(opts$no_self_links)) {
    parts <- c(parts, "--no-self-links")
  }

  parts <- .append_specs(parts, opts, OUTPUT_OPTIONS)

  if (isTRUE(opts$verbosity_level > 1L)) {
    parts <- c(parts, paste0("-", strrep("v", opts$verbosity_level)))
  }

  if (!is.null(opts$output)) {
    parts <- c(parts, paste("--output", paste(opts$output, collapse = ",")))
  }
  parts <- .append_specs(parts, opts, ALGORITHM_OPTIONS)

  if (!is.null(opts$directed)) {
    parts <- c(parts, if (isTRUE(opts$directed)) "--directed" else "--flow-model undirected")
  }
  parts <- .append_specs(parts, opts, ACCURACY_OPTIONS)

  if (!is.null(opts$fast_hierarchical_solution)) {
    parts <- c(parts, paste0("-", strrep("F", opts$fast_hierarchical_solution)))
  }

  rendered <- paste(parts, collapse = " ")
  if (is.null(args) || !nzchar(args)) {
    rendered
  } else if (length(parts) == 0L) {
    args
  } else {
    paste(args, rendered)
  }
}
