// Generated by scripts/generate_binding_options.py from ./Infomap --print-json-parameters.
// Edit src/io/ParameterCatalog.cpp or interfaces/parameters/overrides.json, then run
// make build-binding-options.

type OutputFormats =
  | "clu"
  | "tree"
  | "ftree"
  | "newick"
  | "json"
  | "csv"
  | "network"
  | "states"
  | "flow";

export type Arguments = Partial<{
  // input
  skipAdjustBipartiteFlow: boolean;
  bipartiteTeleportation: boolean;
  weightThreshold: number;
  noSelfLinks: boolean;
  nodeLimit: number;
  matchableMultilayerIds: number;
  clusterData: string;
  assignToNeighbouringModule: boolean;
  metaData: string;
  metaDataRate: number;
  metaDataUnweighted: boolean;
  noInfomap: boolean;
  // output
  outName: string;
  noFileOutput: boolean;
  tree: boolean;
  ftree: boolean;
  clu: boolean;
  cluLevel: number;
  output: OutputFormats | OutputFormats[];
  hideBipartiteNodes: boolean;
  printAllTrials: boolean;
  noOverwrite: boolean;
  printConfigFingerprint: boolean;
  timingJson: string;
  summaryJson: string;
  manifestJson: string;
  memoryReport: boolean;
  verbose: 1 | 2 | 3;
  silent: boolean;
  // algorithm
  twoLevel: boolean;
  flowModel:
    | "undirected"
    | "directed"
    | "undirdir"
    | "outdirdir"
    | "rawdir"
    | "precomputed";
  directed: boolean;
  recordedTeleportation: boolean;
  useNodeWeightsAsFlow: boolean;
  toNodes: boolean;
  teleportationProbability: number;
  regularized: boolean;
  regularizationStrength: number;
  entropyCorrected: boolean;
  entropyCorrectionStrength: number;
  markovTime: number;
  variableMarkovTime: boolean;
  variableMarkovDamping: number;
  variableMarkovMinScale: number;
  preferredNumberOfModules: number;
  multilayerRelaxRate: number;
  multilayerRelaxLimit: number;
  multilayerRelaxLimitUp: number;
  multilayerRelaxLimitDown: number;
  multilayerRelaxByJsd: boolean;
  // accuracy
  seed: number;
  numTrials: number;
  coreLoopLimit: number;
  coreLevelLimit: number;
  tuneIterationLimit: number;
  coreLoopCodelengthThreshold: number;
  tuneIterationRelativeThreshold: number;
  fastHierarchicalSolution: 1 | 2 | 3;
  converge: boolean;
  preferModularSolution: boolean;
  numRandomMoves: number;
  maxDegreeForRandomMoves: number;
  // about
  help: boolean | "advanced";
  version: boolean;
}>;

export default function argumentsToString(args: Arguments) {
  let result = "";

  if (args.skipAdjustBipartiteFlow) result += " --skip-adjust-bipartite-flow";

  if (args.bipartiteTeleportation) result += " --bipartite-teleportation";

  if (args.weightThreshold != null)
    result += " --weight-threshold " + args.weightThreshold;

  if (args.noSelfLinks) result += " --no-self-links";

  if (args.nodeLimit != null) result += " --node-limit " + args.nodeLimit;

  if (args.matchableMultilayerIds != null)
    result += " --matchable-multilayer-ids " + args.matchableMultilayerIds;

  if (args.clusterData != null) result += " --cluster-data " + args.clusterData;

  if (args.assignToNeighbouringModule)
    result += " --assign-to-neighbouring-module";

  if (args.metaData != null) result += " --meta-data " + args.metaData;

  if (args.metaDataRate != null)
    result += " --meta-data-rate " + args.metaDataRate;

  if (args.metaDataUnweighted) result += " --meta-data-unweighted";

  if (args.noInfomap) result += " --no-infomap";

  if (args.outName != null) result += " --out-name " + args.outName;

  if (args.noFileOutput) result += " --no-file-output";

  if (args.tree) result += " --tree";

  if (args.ftree) result += " --ftree";

  if (args.clu) result += " --clu";

  if (args.cluLevel != null) result += " --clu-level " + args.cluLevel;

  if (args.output != null) {
    if (typeof args.output === "string") result += " --output " + args.output;
    else result += " --output " + args.output.join(",");
  }

  if (args.hideBipartiteNodes) result += " --hide-bipartite-nodes";

  if (args.printAllTrials) result += " --print-all-trials";

  if (args.noOverwrite) result += " --no-overwrite";

  if (args.printConfigFingerprint) result += " --print-config-fingerprint";

  if (args.timingJson != null) result += " --timing-json " + args.timingJson;

  if (args.summaryJson != null) result += " --summary-json " + args.summaryJson;

  if (args.manifestJson != null)
    result += " --manifest-json " + args.manifestJson;

  if (args.memoryReport) result += " --memory-report";

  if (args.verbose) result += " -" + "v".repeat(args.verbose);

  if (args.silent) result += " --silent";

  if (args.twoLevel) result += " --two-level";

  if (args.flowModel != null) result += " --flow-model " + args.flowModel;

  if (args.directed) result += " --directed";

  if (args.recordedTeleportation) result += " --recorded-teleportation";

  if (args.useNodeWeightsAsFlow) result += " --use-node-weights-as-flow";

  if (args.toNodes) result += " --to-nodes";

  if (args.teleportationProbability != null)
    result += " --teleportation-probability " + args.teleportationProbability;

  if (args.regularized) result += " --regularized";

  if (args.regularizationStrength != null)
    result += " --regularization-strength " + args.regularizationStrength;

  if (args.entropyCorrected) result += " --entropy-corrected";

  if (args.entropyCorrectionStrength != null)
    result +=
      " --entropy-correction-strength " + args.entropyCorrectionStrength;

  if (args.markovTime != null) result += " --markov-time " + args.markovTime;

  if (args.variableMarkovTime) result += " --variable-markov-time";

  if (args.variableMarkovDamping != null)
    result += " --variable-markov-damping " + args.variableMarkovDamping;

  if (args.variableMarkovMinScale != null)
    result += " --variable-markov-min-scale " + args.variableMarkovMinScale;

  if (args.preferredNumberOfModules != null)
    result += " --preferred-number-of-modules " + args.preferredNumberOfModules;

  if (args.multilayerRelaxRate != null)
    result += " --multilayer-relax-rate " + args.multilayerRelaxRate;

  if (args.multilayerRelaxLimit != null)
    result += " --multilayer-relax-limit " + args.multilayerRelaxLimit;

  if (args.multilayerRelaxLimitUp != null)
    result += " --multilayer-relax-limit-up " + args.multilayerRelaxLimitUp;

  if (args.multilayerRelaxLimitDown != null)
    result += " --multilayer-relax-limit-down " + args.multilayerRelaxLimitDown;

  if (args.multilayerRelaxByJsd) result += " --multilayer-relax-by-jsd";

  if (args.seed != null) result += " --seed " + args.seed;

  if (args.numTrials != null) result += " --num-trials " + args.numTrials;

  if (args.coreLoopLimit != null)
    result += " --core-loop-limit " + args.coreLoopLimit;

  if (args.coreLevelLimit != null)
    result += " --core-level-limit " + args.coreLevelLimit;

  if (args.tuneIterationLimit != null)
    result += " --tune-iteration-limit " + args.tuneIterationLimit;

  if (args.coreLoopCodelengthThreshold != null)
    result +=
      " --core-loop-codelength-threshold " + args.coreLoopCodelengthThreshold;

  if (args.tuneIterationRelativeThreshold != null)
    result +=
      " --tune-iteration-relative-threshold " +
      args.tuneIterationRelativeThreshold;

  if (args.fastHierarchicalSolution)
    result += " -" + "F".repeat(args.fastHierarchicalSolution);

  if (args.converge) result += " --converge";

  if (args.preferModularSolution) result += " --prefer-modular-solution";

  if (args.numRandomMoves != null)
    result += " --num-random-moves " + args.numRandomMoves;

  if (args.maxDegreeForRandomMoves != null)
    result += " --max-degree-for-random-moves " + args.maxDegreeForRandomMoves;

  if (args.help) result += args.help === "advanced" ? " -hh" : " -h";

  if (args.version) result += " --version";

  return result;
}
