#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

from parameter_catalog import GROUPS, ParameterCatalog


REPO_ROOT = Path(__file__).resolve().parents[1]
OVERRIDES = REPO_ROOT / "interfaces" / "parameters" / "overrides.json"

PYTHON_OUT = Path("interfaces/python/src/infomap/_options.py")
R_OUT = Path("interfaces/R/infomap/R/options.R")
TS_OUT = Path("interfaces/js/src/arguments.ts")


def load_parameters(infomap_bin: Path) -> list[dict]:
    result = subprocess.run(
        [str(infomap_bin.resolve()), "--print-json-parameters"],
        check=True,
        capture_output=True,
        text=True,
    )
    return json.loads(result.stdout)["parameters"]


def load_overrides() -> dict:
    overrides = json.loads(OVERRIDES.read_text(encoding="utf-8"))
    for language, entries in overrides.get("bindingOnly", {}).items():
        for entry in entries:
            if not entry.get("reason"):
                raise RuntimeError(
                    f"bindingOnly entry for {language}:{entry.get('name')} must include a reason"
                )
    return overrides


def wrap_doc(text: str, prefix: str, width: int = 88) -> list[str]:
    words = text.replace("`", "``").split()
    lines: list[str] = []
    line = prefix
    for word in words:
        candidate = f"{line} {word}" if line.strip() else f"{prefix}{word}"
        if len(candidate) > width and line != prefix:
            lines.append(line.rstrip())
            line = f"{prefix}{word}"
        else:
            line = candidate
    lines.append(line.rstrip() if line.strip() else prefix.rstrip())
    return lines


def generate_python(catalog: ParameterCatalog) -> str:
    grouped = catalog.grouped()
    include_self_links = catalog.binding_only_entry("python", "include_self_links")
    lines = [
        "from __future__ import annotations",
        "",
        "import warnings",
        "from dataclasses import dataclass, fields",
        "",
        "",
        "# Generated by scripts/generate_binding_options.py from ./Infomap --print-json-parameters.",
        "# Edit src/io/ParameterCatalog.cpp or interfaces/parameters/overrides.json, then run",
        "# make build-binding-options.",
        "",
    ]
    for const, value in catalog.python_default_constants():
        lines.append(f"{const} = {value}")
    lines.append("")
    lines.append("")

    for group in GROUPS:
        spec_name = f"_{group.upper()}_OPTION_SPECS"
        lines.append(f"{spec_name} = (")
        for param in grouped[group]:
            if not param.uses_generic_spec():
                continue
            name = param.name("python")
            kind = param.spec_kind
            include = "None" if kind == "flag" else param.python_include_expr()
            lines.append(f'    ("{kind}", "{name}", "{param.flag}", {include}),')
        lines.append(")")
        lines.append("")

    lines.extend(
        [
            "",
            "def _append_option_specs(parts, options, specs):",
            "    for option_type, option_name, flag, include in specs:",
            "        value = options[option_name]",
            '        if option_type == "flag":',
            "            if value:",
            "                parts.append(flag)",
            "            continue",
            "        if include(value):",
            '            parts.append(f"{flag} {value}")',
            "",
            "",
            "def _join_args(base_args, parts):",
            "    if not parts:",
            '        return "" if base_args is None else base_args',
            "    if not base_args:",
            "        return f\" {' '.join(parts)}\"",
            "    return f\"{base_args} {' '.join(parts)}\"",
            "",
            "",
            "@dataclass(slots=True)",
            "class InfomapOptions:",
            '    """Reusable Infomap keyword options.',
            "",
            "    This class mirrors the keyword arguments accepted by :class:`infomap.Infomap`",
            "    and :meth:`infomap.Infomap.run`. Use :meth:`to_args` to render command-line",
            "    flags, :meth:`from_mapping` to construct options from existing keyword",
            "    dicts, or the convenience methods :meth:`infomap.Infomap.from_options` and",
            "    :meth:`infomap.Infomap.run_with_options` to apply a reusable configuration.",
            "",
            "    Parameters",
            "    ----------",
        ]
    )
    for group in GROUPS:
        for param in grouped[group]:
            name = param.name("python")
            description = param.python_doc_description()
            lines.append(f"    {name} : {param.python_doc_type()}")
            lines.extend(wrap_doc(description, "        "))
    lines.append("    include_self_links : bool, optional")
    lines.extend(
        wrap_doc(
            "Deprecated. Self-links are included by default; use no_self_links=True to exclude them.",
            "        ",
        )
    )
    lines.extend(['    """', ""])
    for group in GROUPS:
        lines.append(f"    # {group.lower()}")
        if group == "Input":
            lines.append(
                f"    include_self_links: {include_self_links.type} = {include_self_links.default}"
            )
        for param in grouped[group]:
            lines.append(
                f"    {param.name('python')}: {param.python_type()} = {param.python_default_expr()}"
            )
    lines.extend(
        [
            "",
            "    @classmethod",
            "    def from_mapping(cls, mapping):",
            "        return cls(**{name: mapping[name] for name in _OPTION_FIELD_NAMES if name in mapping})",
            "",
            "    def to_kwargs(self):",
            "        return {name: getattr(self, name) for name in _OPTION_FIELD_NAMES}",
            "",
            "    def to_args(self, base_args: str | None = None):",
            "        options = self.to_kwargs()",
            "        rendered_args = []",
            "",
            "        if self.include_self_links is not None:",
            "            warnings.warn(",
            '                "include_self_links is deprecated, use no_self_links to exclude self-links",',
            "                DeprecationWarning,",
            "                stacklevel=2,",
            "            )",
            "",
            "        _append_option_specs(rendered_args, options, _INPUT_OPTION_SPECS)",
            "",
            "        if (self.include_self_links is not None and not self.include_self_links) or self.no_self_links:",
            '            rendered_args.append("--no-self-links")',
            "",
            "        _append_option_specs(rendered_args, options, _OUTPUT_OPTION_SPECS)",
            "",
            "        if self.verbosity_level > 1:",
            "            rendered_args.append(f\"-{'v' * self.verbosity_level}\")",
            "",
            "        if self.output is not None:",
            "            rendered_args.append(f\"--output {','.join(self.output)}\")",
            "",
            "        _append_option_specs(rendered_args, options, _ALGORITHM_OPTION_SPECS)",
            "",
            "        if self.directed is not None:",
            '            rendered_args.append("--directed" if self.directed else "--flow-model undirected")',
            "",
            "        _append_option_specs(rendered_args, options, _ACCURACY_OPTION_SPECS)",
            "",
            "        if self.fast_hierarchical_solution is not None:",
            "            rendered_args.append(f\"-{'F' * self.fast_hierarchical_solution}\")",
            "",
            "        return _join_args(base_args, rendered_args)",
            "",
            "",
            "_OPTION_FIELD_NAMES = tuple(field.name for field in fields(InfomapOptions))",
            "",
            "",
            "def _construct_args(",
            "    args=None,",
        ]
    )
    for group in GROUPS:
        lines.append(f"    # {group.lower()}")
        if group == "Input":
            lines.append(f"    include_self_links={include_self_links.default},")
        for param in grouped[group]:
            lines.append(f"    {param.name('python')}={param.python_default_expr()},")
    lines.extend(
        [
            "):",
            "    return InfomapOptions.from_mapping(locals()).to_args(base_args=args)",
            "",
        ]
    )
    return "\n".join(lines)


def generate_r(catalog: ParameterCatalog) -> str:
    grouped = catalog.grouped()
    include_self_links = catalog.binding_only_entry("r", "include_self_links")
    lines = [
        "# Defaults, option specs, and CLI argument construction.",
        "# Generated by scripts/generate_binding_options.py from ./Infomap --print-json-parameters.",
        "# Edit src/io/ParameterCatalog.cpp or interfaces/parameters/overrides.json, then run",
        "# make build-binding-options.",
        "",
    ]
    for const, value in catalog.r_default_constants():
        lines.append(f"{const} <- {value}")
    lines.extend(
        [
            "",
            ".skip_when_null <- function(x) !is.null(x)",
            ".skip_when_not_equal <- function(default) function(x) !identical(x, default)",
            "",
        ]
    )
    for group in GROUPS:
        lines.append(f"{group.upper()}_OPTIONS <- list(")
        specs = []
        for param in grouped[group]:
            if not param.uses_generic_spec():
                continue
            kind = param.spec_kind
            name = param.name("r")
            default = param.r_default()
            include = "" if kind == "flag" else f", include = {param.r_include_expr()}"
            specs.append(
                f'  list(type = "{kind}", name = "{name}", flag = "{param.flag}", default = {default}{include})'
            )
        lines.append(",\n".join(specs))
        lines.append(")")
        lines.append("")
    fields = []
    for group in GROUPS:
        if group == "Input":
            fields.append("include_self_links")
        fields.extend(param.name("r") for param in grouped[group])
    lines.append("OPTION_FIELD_NAMES <- c(")
    for i in range(0, len(fields), 4):
        lines.append(
            "  "
            + ", ".join(json.dumps(field) for field in fields[i : i + 4])
            + ("," if i + 4 < len(fields) else "")
        )
    lines.append(")")
    lines.append("")
    lines.append("OPTION_DEFAULTS <- list(")
    defaults = [f"include_self_links = {include_self_links.default}"]
    for group in GROUPS:
        for param in grouped[group]:
            defaults.append(f"{param.name('r')} = {param.r_default()}")
    for i, default in enumerate(defaults):
        suffix = "," if i + 1 < len(defaults) else ""
        lines.append(f"  {default}{suffix}")
    lines.append(")")
    lines.extend(
        [
            "",
            "#' Build a reusable Infomap options list",
            "#'",
            "#' Returns a named list with one entry per Infomap CLI option. All",
            "#' arguments default to the Infomap-internal defaults, so callers only",
            "#' need to supply the options they want to override. The returned list",
            "#' is accepted by [Infomap()] and `Infomap$run()`.",
            "#'",
            "#' Argument names mirror the Infomap CLI flags (with hyphens replaced by",
            "#' underscores) and the keyword arguments accepted by the Python interface.",
            "#'",
            "#' @param ... Named option overrides. See **Options** below.",
            "#'",
            "#' @section Options:",
        ]
    )
    for group in GROUPS:
        lines.append(f"#' {group}")
        lines.append("#' \\describe{")
        if group == "Input":
            lines.append(
                "#'   \\item{`include_self_links`}{Deprecated. Self-links are included by default; use `no_self_links = TRUE` to exclude them.}"
            )
        for param in grouped[group]:
            name = param.name("r")
            desc = (
                param.description.replace("\\", "\\\\")
                .replace("{", "\\{")
                .replace("}", "\\}")
                .replace("[", "\\[")
                .replace("]", "\\]")
            )
            lines.append(f"#'   \\item{{`{name}`}}{{{desc}}}")
        lines.append("#' }")
        lines.append("#'")
    lines.extend(
        [
            "#' @return A named list of options.",
            "#' @examples",
            "#' opts <- infomap_options(num_trials = 10, two_level = TRUE)",
            "#' im <- Infomap(opts = opts, silent = TRUE)",
            "#' @export",
            "infomap_options <- function(...) {",
            "  overrides <- list(...)",
            "  unknown <- setdiff(names(overrides), OPTION_FIELD_NAMES)",
            "  if (length(unknown) > 0L) {",
            "    stop(",
            '      "Unknown infomap options: ", paste(unknown, collapse = ", "),',
            '      ". See ?infomap_options for the full list.",',
            "      call. = FALSE",
            "    )",
            "  }",
            "  opts <- OPTION_DEFAULTS",
            "  for (name in names(overrides)) {",
            "    opts[[name]] <- overrides[[name]]",
            "  }",
            "  opts",
            "}",
            "",
            ".append_specs <- function(parts, opts, specs) {",
            "  for (spec in specs) {",
            "    value <- opts[[spec$name]]",
            '    if (identical(spec$type, "flag")) {',
            "      if (isTRUE(value)) parts <- c(parts, spec$flag)",
            "      next",
            "    }",
            "    include <- if (is.null(spec$include)) function(v) !is.null(v) && !identical(v, spec$default) else spec$include",
            "    if (isTRUE(include(value))) {",
            "      parts <- c(parts, paste(spec$flag, format_value(value)))",
            "    }",
            "  }",
            "  parts",
            "}",
            "",
            "format_value <- function(value) {",
            "  if (is.character(value)) return(value)",
            '  if (is.logical(value)) return(if (isTRUE(value)) "true" else "false")',
            "  if (is.numeric(value)) {",
            "    if (is.integer(value) || (is.finite(value) && value == as.integer(value))) {",
            "      return(format(as.integer(value), scientific = FALSE))",
            "    }",
            "    return(format(value, scientific = FALSE, trim = TRUE))",
            "  }",
            "  as.character(value)",
            "}",
            "",
            "#' Render an Infomap options list to a CLI argument string",
            "#'",
            "#' This is exported for advanced use; most callers should pass options",
            "#' directly to [Infomap()] or `Infomap$run()`.",
            "#'",
            "#' @param args Optional raw argument string to prepend.",
            "#' @param opts Options list from [infomap_options()] (or `NULL`).",
            "#'",
            "#' @return A single character string of CLI arguments.",
            "#' @export",
            "construct_args <- function(args = NULL, opts = NULL) {",
            "  if (is.null(opts)) opts <- OPTION_DEFAULTS",
            "  parts <- character(0)",
            "",
            "  if (!is.null(opts$include_self_links)) {",
            "    .Deprecated(",
            '      new = "no_self_links",',
            '      package = "infomap",',
            '      old = "include_self_links",',
            '      msg = "include_self_links is deprecated; use no_self_links = TRUE to exclude self-links."',
            "    )",
            "  }",
            "",
            "  parts <- .append_specs(parts, opts, INPUT_OPTIONS)",
            "",
            "  if ((!is.null(opts$include_self_links) && !isTRUE(opts$include_self_links)) ||",
            "      isTRUE(opts$no_self_links)) {",
            '    parts <- c(parts, "--no-self-links")',
            "  }",
            "",
            "  parts <- .append_specs(parts, opts, OUTPUT_OPTIONS)",
            "",
            "  if (isTRUE(opts$verbosity_level > 1L)) {",
            '    parts <- c(parts, paste0("-", strrep("v", opts$verbosity_level)))',
            "  }",
            "",
            "  if (!is.null(opts$output)) {",
            '    parts <- c(parts, paste("--output", paste(opts$output, collapse = ",")))',
            "  }",
            "  parts <- .append_specs(parts, opts, ALGORITHM_OPTIONS)",
            "",
            "  if (!is.null(opts$directed)) {",
            '    parts <- c(parts, if (isTRUE(opts$directed)) "--directed" else "--flow-model undirected")',
            "  }",
            "  parts <- .append_specs(parts, opts, ACCURACY_OPTIONS)",
            "",
            "  if (!is.null(opts$fast_hierarchical_solution)) {",
            '    parts <- c(parts, paste0("-", strrep("F", opts$fast_hierarchical_solution)))',
            "  }",
            "",
            '  rendered <- paste(parts, collapse = " ")',
            "  if (is.null(args) || !nzchar(args)) {",
            "    rendered",
            "  } else if (length(parts) == 0L) {",
            "    args",
            "  } else {",
            "    paste(args, rendered)",
            "  }",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def generate_ts(catalog: ParameterCatalog) -> str:
    grouped = catalog.grouped()
    about_options = catalog.binding_only("ts")
    output_param = next(param for param in catalog.parameters if param.flag == "--output")
    output_choices = output_param.choices or []
    lines = [
        "// Generated by scripts/generate_binding_options.py from ./Infomap --print-json-parameters.",
        "// Edit src/io/ParameterCatalog.cpp or interfaces/parameters/overrides.json, then run",
        "// make build-binding-options.",
        "",
        "type OutputFormats =",
    ]
    for choice in output_choices:
        lines.append(f'  | "{choice}"')
    lines[-1] += ";"
    lines.extend(["", "export type Arguments = Partial<{"])
    for group in GROUPS:
        lines.append(f"  // {group.lower()}")
        for param in grouped[group]:
            name = param.name("ts")
            typ = param.ts_type()
            if typ.startswith("\n"):
                lines.append(f"  {name}:{typ};")
            else:
                lines.append(f"  {name}: {typ};")
    lines.append("  // about")
    for entry in about_options:
        lines.append(f"  {entry.name}: {entry.type};")
    lines.extend(
        [
            "}>;",
            "",
            "export default function argumentsToString(args: Arguments) {",
            '  let result = "";',
            "",
        ]
    )

    def append_result(condition: str, expression: str) -> None:
        one_line = f"  if ({condition}) result += {expression};"
        if len(one_line) <= 80:
            lines.append(one_line)
            return

        lines.append(f"  if ({condition})")
        assignment = f"    result += {expression};"
        if len(assignment) <= 80:
            lines.append(assignment)
            return

        lines.append("    result +=")
        if len(f"      {expression};") <= 80:
            lines.append(f"      {expression};")
            return
        if " + " in expression:
            left, right = expression.rsplit(" + ", 1)
            if len(f"      {left} +") <= 80 and len(f"      {right};") <= 80:
                lines.append(f"      {left} +")
                lines.append(f"      {right};")
                return
        lines.append(f"      {expression};")

    for group in GROUPS:
        for param in grouped[group]:
            flag = param.flag
            name = param.name("ts")
            if param.render_policy == "repeated_short" and flag == "--verbose":
                append_result(
                    f"args.{name}", f'" -" + "v".repeat(args.{name})'
                )
            elif param.render_policy == "repeated_short":
                append_result(
                    f"args.{name}", f'" -" + "F".repeat(args.{name})'
                )
            elif param.render_policy == "comma_list":
                lines.extend(
                    [
                        f"  if (args.{name} != null) {{",
                        f'    if (typeof args.{name} === "string") result += " --output " + args.{name};',
                        f'    else result += " --output " + args.{name}.join(",");',
                        "  }",
                    ]
                )
            elif not param.required:
                append_result(f"args.{name}", f'" {flag}"')
            else:
                append_result(
                    f"args.{name} != null", f'" {flag} " + args.{name}'
                )
            lines.append("")
    for entry in about_options:
        if entry.name == "help":
            lines.append(
                '  if (args.help) result += args.help === "advanced" ? " -hh" : " -h";'
            )
        elif entry.name == "version":
            lines.append('  if (args.version) result += " --version";')
        else:
            raise RuntimeError(
                f"Unsupported TypeScript binding-only option: {entry.name}"
            )
        lines.append("")
    lines.extend(["  return result;", "}", ""])
    return "\n".join(lines)


def outputs(infomap_bin: Path) -> dict[Path, str]:
    overrides = load_overrides()
    catalog = ParameterCatalog(load_parameters(infomap_bin), overrides)
    return {
        PYTHON_OUT: generate_python(catalog),
        R_OUT: generate_r(catalog),
        TS_OUT: generate_ts(catalog),
    }


def write_outputs(generated: dict[Path, str], output_root: Path) -> None:
    for rel_path, text in generated.items():
        path = output_root / rel_path
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")


def check_outputs(generated: dict[Path, str], output_root: Path) -> int:
    failures = []
    for rel_path, text in generated.items():
        path = output_root / rel_path
        if not path.exists() or path.read_text(encoding="utf-8") != text:
            failures.append(rel_path)
    if not failures:
        print("Tracked binding option outputs are fresh.")
        return 0
    if sys.platform and "GITHUB_ACTIONS" in __import__("os").environ:
        print(
            "::error title=Tracked binding option outputs are stale::Run make build-binding-options and commit the updated files."
        )
    print("Tracked binding option outputs are stale:")
    for path in failures:
        print(f"  {path}")
    print()
    print("Run: make build-binding-options")
    return 1


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--infomap-bin", default="./Infomap")
    parser.add_argument("--output-root", default=".")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    generated = outputs(Path(args.infomap_bin))
    output_root = Path(args.output_root)
    if args.check:
        return check_outputs(generated, output_root)
    write_outputs(generated, output_root)
    for path in generated:
        print(f"Updated {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
