from __future__ import annotations

import os
import sys
import warnings
from collections.abc import Mapping
from dataclasses import dataclass, fields, replace
from typing import Literal


# Generated by scripts/generate_binding_options.py from ./Infomap --print-json-parameters.
# Edit src/io/ParameterCatalog.cpp or interfaces/parameters/overrides.json, then run
# make build-binding-options.

_PACKAGE_PREFIX = os.path.dirname(os.path.abspath(__file__)) + os.sep


def _external_stacklevel() -> int:
    # Compute a warnings.warn stacklevel that attributes the warning to
    # the first caller frame outside this package, whichever public entry
    # point (Infomap(), Infomap.run(), infomap.run(), Options.to_args())
    # reached this module. Python 3.12's skip_file_prefixes does this
    # natively; the supported floor is 3.11.
    frame = sys._getframe(1)
    level = 1
    while frame is not None and frame.f_code.co_filename.startswith(
        _PACKAGE_PREFIX
    ):
        frame = frame.f_back
        level += 1
    return level

OutputFormat = Literal[
    "clu", "tree", "ftree", "newick", "json", "csv", "network", "states", "flow"
]

FlowModel = Literal[
    "undirected", "directed", "undirdir", "outdirdir", "rawdir", "precomputed"
]

_ADVANCED_TIER_KWARGS = {
    "skip_adjust_bipartite_flow": (False, False, "keep", None),
    "bipartite_teleportation": (False, False, "keep", None),
    "weight_threshold": (None, None, "keep", None),
    "no_self_links": (False, False, "keep", None),
    "node_limit": (None, None, "keep", None),
    "matchable_multilayer_ids": (None, None, "keep", None),
    "cluster_data": (None, None, "keep", None),
    "assign_to_neighbouring_module": (False, False, "keep", None),
    "meta_data": (None, None, "keep", None),
    "meta_data_rate": (1.0, 1.0, "keep", None),
    "meta_data_unweighted": (False, False, "keep", None),
    "no_infomap": (False, False, "keep", None),
    "out_name": (None, None, "args-only", "Use Result.write_tree/write_flow_tree/write_clu (write_clu takes depth_level) or Network.write_pajek/write_state_network. The flag only acts when an output directory is passed via the raw args escape hatch."),
    "no_file_output": (False, False, "args-only", "Use Result.write_tree/write_flow_tree/write_clu (write_clu takes depth_level) or Network.write_pajek/write_state_network. The flag only acts when an output directory is passed via the raw args escape hatch."),
    "tree": (False, False, "args-only", "Use Result.write_tree/write_flow_tree/write_clu (write_clu takes depth_level) or Network.write_pajek/write_state_network. The flag only acts when an output directory is passed via the raw args escape hatch."),
    "ftree": (False, False, "args-only", "Use Result.write_tree/write_flow_tree/write_clu (write_clu takes depth_level) or Network.write_pajek/write_state_network. The flag only acts when an output directory is passed via the raw args escape hatch."),
    "clu": (False, False, "args-only", "Use Result.write_tree/write_flow_tree/write_clu (write_clu takes depth_level) or Network.write_pajek/write_state_network. The flag only acts when an output directory is passed via the raw args escape hatch."),
    "clu_level": (None, None, "args-only", "Use Result.write_tree/write_flow_tree/write_clu (write_clu takes depth_level) or Network.write_pajek/write_state_network. The flag only acts when an output directory is passed via the raw args escape hatch."),
    "output": (None, None, "args-only", "Use Result.write_tree/write_flow_tree/write_clu (write_clu takes depth_level) or Network.write_pajek/write_state_network. The flag only acts when an output directory is passed via the raw args escape hatch."),
    "hide_bipartite_nodes": (False, False, "args-only", "It projects the secondary (type-B) bipartite nodes out of what result.write_tree/write_clu emit, leaving the in-memory result covering both node types. Set it via Options and write from the Result to use it."),
    "print_all_trials": (False, False, "args-only", "Use Result.write_tree/write_flow_tree/write_clu (write_clu takes depth_level) or Network.write_pajek/write_state_network. The flag only acts when an output directory is passed via the raw args escape hatch."),
    "no_overwrite": (False, False, "args-only", "Use Result.write_tree/write_flow_tree/write_clu (write_clu takes depth_level) or Network.write_pajek/write_state_network. The flag only acts when an output directory is passed via the raw args escape hatch."),
    "print_config_fingerprint": (False, False, "remove", "A print-and-exit CLI diagnostic; run the infomap binary."),
    "timing_json": (None, None, "keep", None),
    "summary_json": (None, None, "keep", None),
    "manifest_json": (None, None, "keep", None),
    "memory_report": (False, False, "keep", None),
    "trial_offset": (None, None, "keep", None),
    "trial_results": (None, None, "keep", None),
    "no_final_output": (False, False, "keep", None),
    "verbosity_level": (1, 1, "remove", "A DEBUG-enabled 'infomap' logger (infomap.enable_log(logging.DEBUG)) raises engine verbosity; logger levels filter the records."),
    "silent": (True, False, "remove", "The Python API is quiet by default; logging is the control. Attach handlers to logging.getLogger('infomap') (e.g. infomap.enable_log()) for the engine log."),
    "flow_model": (None, None, "keep", None),
    "recorded_teleportation": (False, False, "keep", None),
    "use_node_weights_as_flow": (False, False, "keep", None),
    "to_nodes": (False, False, "keep", None),
    "teleportation_probability": (0.15, 0.15, "keep", None),
    "max_flow_iterations": (400, 400, "keep", None),
    "min_flow_iterations": (50, 50, "keep", None),
    "flow_tolerance": (1e-15, 1e-15, "keep", None),
    "regularized": (False, False, "keep", None),
    "regularization_strength": (1.0, 1.0, "keep", None),
    "entropy_corrected": (False, False, "keep", None),
    "entropy_correction_strength": (1.0, 1.0, "keep", None),
    "variable_markov_time": (False, False, "keep", None),
    "variable_markov_damping": (1.0, 1.0, "keep", None),
    "variable_markov_min_scale": (1.0, 1.0, "keep", None),
    "preferred_number_of_modules": (None, None, "keep", None),
    "preferred_number_of_levels": (None, None, "keep", None),
    "preferred_number_of_levels_strength": (1.0, 1.0, "keep", None),
    "multilayer_relax_rate": (0.15, 0.15, "keep", None),
    "multilayer_relax_limit": (-1, -1, "keep", None),
    "multilayer_relax_limit_up": (-1, -1, "keep", None),
    "multilayer_relax_limit_down": (-1, -1, "keep", None),
    "multilayer_relax_by_jsd": (False, False, "keep", None),
    "multilayer_relax_to_self": (False, False, "keep", None),
    "core_loop_limit": (10, 10, "keep", None),
    "core_level_limit": (None, None, "keep", None),
    "tune_iteration_limit": (None, None, "keep", None),
    "core_loop_codelength_threshold": (1e-10, 1e-10, "keep", None),
    "tune_iteration_relative_threshold": (1e-05, 1e-05, "keep", None),
    "fast_hierarchical_solution": (None, None, "keep", None),
    "inner_parallelization": (False, False, "keep", None),
    "parallel_trials": (False, False, "keep", None),
    "converge": (False, False, "keep", None),
    "num_threads": (None, None, "keep", None),
    "threads": (None, None, "remove", "Use num_threads; threads is a redundant alias of the same engine option."),
    "prefer_modular_solution": (False, False, "keep", None),
    "num_random_moves": (5, 5, "keep", None),
    "max_degree_for_random_moves": (2, 2, "keep", None),
}


def _warn_advanced_tier_kwargs(passed, context):
    # Advanced-tier keywords are docs-only deprecated on the Infomap()/run()
    # signatures (issue #741) and move off them in 3.0. Emit a
    # PendingDeprecationWarning -- silent by default, so it nags no one until
    # 3.0 nears -- when one is set to a non-default value on a direct call.
    # Internal funnels (the Options path builds Infomap(**resolved), the graph
    # adapters, the from_* class methods) reach the same methods from inside
    # the package; the caller-frame check skips them so only user-typed
    # keywords are flagged.
    caller = sys._getframe(2)
    if caller.f_code.co_filename.startswith(_PACKAGE_PREFIX):
        return
    baseline = 1 if context == "run" else 0
    for name, spec in _ADVANCED_TIER_KWARGS.items():
        default = spec[baseline]
        if passed.get(name, default) != default:
            action, replacement = spec[2], spec[3]
            lead = (
                f"'{name}' is deprecated on the Infomap() and run() "
                "signatures and leaves them in 3.0. "
            )
            if action in ("keep", "alias"):
                guidance = (
                    "Pass it via Options to infomap.run() or "
                    "Network.run() instead."
                )
            elif replacement is not None:
                guidance = replacement
            else:
                guidance = ""
            warnings.warn(
                lead + guidance, PendingDeprecationWarning, stacklevel=3
            )


_OPTION_DOMAINS = {
    "weight_threshold": (0.0, None),
    "node_limit": (1, None),
    "matchable_multilayer_ids": (1, None),
    "meta_data_rate": (0.0, None),
    "clu_level": (-1, None),
    "trial_offset": (0, None),
    "teleportation_probability": (0.0, 1.0),
    "max_flow_iterations": (1, None),
    "min_flow_iterations": (0, None),
    "flow_tolerance": (0.0, None),
    "regularization_strength": (0.0, None),
    "entropy_correction_strength": (0.0, None),
    "markov_time": (0.0, None),
    "variable_markov_damping": (0.0, 1.0),
    "preferred_number_of_modules": (1, None),
    "preferred_number_of_levels": (1, None),
    "preferred_number_of_levels_strength": (0.0, None),
    "multilayer_relax_rate": (0.0, 1.0),
    "seed": (1, None),
    "num_trials": (1, None),
    "core_loop_limit": (1, None),
    "core_level_limit": (0, None),
    "tune_iteration_limit": (0, None),
    "core_loop_codelength_threshold": (0.0, None),
    "tune_iteration_relative_threshold": (0.0, None),
    "num_random_moves": (0, None),
    "max_degree_for_random_moves": (0, None),
}


def _validate_option_domains(options):
    """Reject out-of-range numeric options with a clear ValueError.

    The engine parser rejects an out-of-domain value (seed < 1, a
    probability outside [0, 1], a negative markov time, ...) with a generic
    "Cannot parse '<value>' as argument to option '<flag>'" -- misleading,
    since the value parses fine as a number and only violates the option's
    range. Catch it here first, naming the option and its valid range. Bounds
    are inclusive, mirroring the C++ parser (reject value < min or > max).
    """
    for name, (low, high) in _OPTION_DOMAINS.items():
        value = options.get(name)
        if (
            value is None
            or isinstance(value, bool)
            or not isinstance(value, (int, float))
        ):
            continue
        if (low is not None and value < low) or (
            high is not None and value > high
        ):
            if low is not None and high is not None:
                bounds = f"between {low} and {high} (inclusive)"
            elif low is not None:
                bounds = f">= {low}"
            else:
                bounds = f"<= {high}"
            raise ValueError(
                f"{name}={value!r} is out of range: {name} must be {bounds}."
            )


_OPTION_CHOICES = {
    "output": (("clu", "tree", "ftree", "newick", "json", "csv", "network", "states", "flow",), True),
    "flow_model": (("undirected", "directed", "undirdir", "outdirdir", "rawdir", "precomputed",), False),
}


def _validate_option_choices(options):
    """Reject unrecognized choice/enum options with a clear ValueError.

    Mirrors the catalog's allowed value set (the same values the type
    checker sees via the generated Literals). Scalar choices (flow_model)
    are checked directly; sequence choices (output) are checked per element.
    num_threads is validated here too: 'auto' or a positive integer.
    """
    for name, (choices, is_sequence) in _OPTION_CHOICES.items():
        value = options.get(name)
        if value is None:
            continue
        if is_sequence and isinstance(value, str):
            # A single format string is a natural guess, but a sequence
            # choice iterates it per character ('tree' -> 't','r',...),
            # yielding a baffling "'t' is not valid". Steer to a list.
            hint = f"[{value!r}]" if value in choices else "['tree', 'clu']"
            raise ValueError(
                f"{name}={value!r} must be a list or tuple of formats "
                f"(e.g. {name}={hint}), not a single string."
            )
        values = value if is_sequence else (value,)
        for item in values:
            if item not in choices:
                allowed = ", ".join(repr(choice) for choice in choices)
                raise ValueError(
                    f"{name}={item!r} is not valid: choose one of {allowed}."
                )
    num_threads = options.get("num_threads")
    if num_threads is not None:
        valid = (
            num_threads == "auto"
            or (
                isinstance(num_threads, int)
                and not isinstance(num_threads, bool)
                and num_threads > 0
            )
            or (
                isinstance(num_threads, str)
                and num_threads.isdigit()
                and int(num_threads) > 0
            )
        )
        if not valid:
            raise ValueError(
                f"num_threads={num_threads!r} is not valid: use 'auto' or a "
                "positive integer."
            )


_INPUT_OPTION_SPECS = (
    ("flag", "skip_adjust_bipartite_flow", "--skip-adjust-bipartite-flow", None),
    ("flag", "bipartite_teleportation", "--bipartite-teleportation", None),
    ("value", "weight_threshold", "--weight-threshold", lambda value: value is not None),
    ("value", "node_limit", "--node-limit", lambda value: value is not None),
    ("value", "matchable_multilayer_ids", "--matchable-multilayer-ids", lambda value: value is not None),
    ("value", "cluster_data", "--cluster-data", lambda value: value is not None),
    ("flag", "assign_to_neighbouring_module", "--assign-to-neighbouring-module", None),
    ("value", "meta_data", "--meta-data", lambda value: value is not None),
    ("value", "meta_data_rate", "--meta-data-rate", lambda value: value != 1.0),
    ("flag", "meta_data_unweighted", "--meta-data-unweighted", None),
    ("flag", "no_infomap", "--no-infomap", None),
)

_OUTPUT_OPTION_SPECS = (
    ("value", "out_name", "--out-name", lambda value: value is not None),
    ("flag", "no_file_output", "--no-file-output", None),
    ("flag", "tree", "--tree", None),
    ("flag", "ftree", "--ftree", None),
    ("flag", "clu", "--clu", None),
    ("value", "clu_level", "--clu-level", lambda value: value is not None),
    ("flag", "hide_bipartite_nodes", "--hide-bipartite-nodes", None),
    ("flag", "print_all_trials", "--print-all-trials", None),
    ("flag", "no_overwrite", "--no-overwrite", None),
    ("flag", "print_config_fingerprint", "--print-config-fingerprint", None),
    ("value", "timing_json", "--timing-json", lambda value: value is not None),
    ("value", "summary_json", "--summary-json", lambda value: value is not None),
    ("value", "manifest_json", "--manifest-json", lambda value: value is not None),
    ("flag", "memory_report", "--memory-report", None),
    ("value", "trial_offset", "--trial-offset", lambda value: value is not None),
    ("value", "trial_results", "--trial-results", lambda value: value is not None),
    ("flag", "no_final_output", "--no-final-output", None),
    ("flag", "silent", "--silent", None),
)

_ALGORITHM_OPTION_SPECS = (
    ("flag", "two_level", "--two-level", None),
    ("value", "flow_model", "--flow-model", lambda value: value is not None),
    ("flag", "recorded_teleportation", "--recorded-teleportation", None),
    ("flag", "use_node_weights_as_flow", "--use-node-weights-as-flow", None),
    ("flag", "to_nodes", "--to-nodes", None),
    ("value", "teleportation_probability", "--teleportation-probability", lambda value: value != 0.15),
    ("value", "max_flow_iterations", "--max-flow-iterations", lambda value: value != 400),
    ("value", "min_flow_iterations", "--min-flow-iterations", lambda value: value != 50),
    ("value", "flow_tolerance", "--flow-tolerance", lambda value: value != 1e-15),
    ("flag", "regularized", "--regularized", None),
    ("value", "regularization_strength", "--regularization-strength", lambda value: value != 1.0),
    ("flag", "entropy_corrected", "--entropy-corrected", None),
    ("value", "entropy_correction_strength", "--entropy-correction-strength", lambda value: value != 1.0),
    ("value", "markov_time", "--markov-time", lambda value: value != 1.0),
    ("flag", "variable_markov_time", "--variable-markov-time", None),
    ("value", "variable_markov_damping", "--variable-markov-damping", lambda value: value != 1.0),
    ("value", "variable_markov_min_scale", "--variable-markov-min-scale", lambda value: value != 1.0),
    ("value", "preferred_number_of_modules", "--preferred-number-of-modules", lambda value: value is not None),
    ("value", "preferred_number_of_levels", "--preferred-number-of-levels", lambda value: value is not None),
    ("value", "preferred_number_of_levels_strength", "--preferred-number-of-levels-strength", lambda value: value != 1.0),
    ("value", "multilayer_relax_rate", "--multilayer-relax-rate", lambda value: value != 0.15),
    ("value", "multilayer_relax_limit", "--multilayer-relax-limit", lambda value: value != -1),
    ("value", "multilayer_relax_limit_up", "--multilayer-relax-limit-up", lambda value: value != -1),
    ("value", "multilayer_relax_limit_down", "--multilayer-relax-limit-down", lambda value: value != -1),
    ("flag", "multilayer_relax_by_jsd", "--multilayer-relax-by-jsd", None),
    ("flag", "multilayer_relax_to_self", "--multilayer-relax-to-self", None),
)

_ACCURACY_OPTION_SPECS = (
    ("value", "seed", "--seed", lambda value: value != 123),
    ("value", "num_trials", "--num-trials", lambda value: value != 1),
    ("value", "core_loop_limit", "--core-loop-limit", lambda value: value != 10),
    ("value", "core_level_limit", "--core-level-limit", lambda value: value is not None),
    ("value", "tune_iteration_limit", "--tune-iteration-limit", lambda value: value is not None),
    ("value", "core_loop_codelength_threshold", "--core-loop-codelength-threshold", lambda value: value != 1e-10),
    ("value", "tune_iteration_relative_threshold", "--tune-iteration-relative-threshold", lambda value: value != 1e-05),
    ("flag", "inner_parallelization", "--inner-parallelization", None),
    ("flag", "parallel_trials", "--parallel-trials", None),
    ("flag", "converge", "--converge", None),
    ("value", "num_threads", "--num-threads", lambda value: value is not None),
    ("value", "threads", "--threads", lambda value: value is not None),
    ("flag", "prefer_modular_solution", "--prefer-modular-solution", None),
    ("value", "num_random_moves", "--num-random-moves", lambda value: value != 5),
    ("value", "max_degree_for_random_moves", "--max-degree-for-random-moves", lambda value: value != 2),
)


def _append_option_specs(parts, options, specs):
    for option_type, option_name, flag, include in specs:
        value = options[option_name]
        if option_type == "flag":
            if value:
                parts.append(flag)
            continue
        if include(value):
            parts.append(f"{flag} {value}")


def _join_args(base_args, parts):
    if not parts:
        return "" if base_args is None else base_args
    if not base_args:
        return f" {' '.join(parts)}"
    return f"{base_args} {' '.join(parts)}"


class _OptionsMeta(type):
    # Intercept construction so an unknown keyword gets the same
    # actionable 'did you mean' guidance as infomap.run(), instead of
    # the bare dataclass 'unexpected keyword argument' TypeError.
    def __call__(cls, *args, **kwargs):
        unknown = [key for key in kwargs if key not in _OPTION_FIELD_NAMES]
        if unknown:
            import difflib

            rendered = []
            for key in unknown:
                near = difflib.get_close_matches(key, _OPTION_FIELD_NAMES, n=1)
                rendered.append(
                    f"{key!r}"
                    + (f" (did you mean {near[0]!r}?)" if near else "")
                )
            raise TypeError(
                "Options() got unknown option(s): "
                + ", ".join(rendered)
                + ". See inspect.getdoc(infomap.Options) for the full "
                "list of option names."
            )
        return super().__call__(*args, **kwargs)


@dataclass(frozen=True, slots=True)
class Options(metaclass=_OptionsMeta):
    """Reusable Infomap keyword options.

    This class mirrors the keyword arguments accepted by :class:`infomap.Infomap`
    and :meth:`infomap.Infomap.run`. Construct it like any dataclass
    (``Options(num_trials=10)``) -- unknown keys raise, as usual -- use
    :meth:`to_args` to render command-line flags, or pass an instance to
    :func:`infomap.run` via ``infomap.run(input, options=options)`` to apply a
    reusable configuration.

    A field marked *args-only in library mode* below drives the engine's
    own file writer, which runs only with an output directory passed via
    the raw ``args`` escape hatch; on the normal library surface it writes
    nothing. Write results from the ``Result`` (``result.write_tree`` /
    ``write_clu`` / ...) or the ``Network`` (``write_pajek`` /
    ``write_state_network``) instead.

    Parameters
    ----------
    skip_adjust_bipartite_flow : bool, optional
        Keep flow on bipartite nodes instead of distributing it to primary nodes.
    bipartite_teleportation : bool, optional
        Use bipartite teleportation instead of the default two-step unipartite
        teleportation.
    weight_threshold : float, optional
        Ignore input links with weight below this threshold. Valid range: >= 0.0. Engine
        default: 0.
    no_self_links : bool, optional
        Exclude self-links from the input network.
    node_limit : int, optional
        Read only nodes up to this node id and ignore links connected to higher node
        ids. Valid range: >= 1.
    matchable_multilayer_ids : int, optional
        Construct state ids from node ids and layer ids that stay comparable across
        networks. Set at least to the largest layer id among networks to match. Valid
        range: >= 1.
    cluster_data : str, optional
        Read an initial partition from a clu file or a hierarchy from a tree/ftree file.
        Tree input may use physical or state nodes for higher-order networks.
    assign_to_neighbouring_module : bool, optional
        With --cluster-data, assign nodes missing module ids to a neighboring node's
        module when possible.
    meta_data : str, optional
        Read metadata to encode from a clu-format file.
    meta_data_rate : float, optional
        With --meta-data, set the metadata encoding rate. The default encodes metadata
        at each step. Valid range: >= 0.0.
    meta_data_unweighted : bool, optional
        With --meta-data, encode metadata without weighting by node flow.
    no_infomap : bool, optional
        Skip optimization. Use this to calculate codelength for --cluster-data or to
        print non-modular statistics.
    out_name : str, optional
        Base name for output files, for example [out_directory]/[out-name].tree.

        Args-only in library mode: no effect here -- write from the Result / Network
        (see the note under Parameters below).
    no_file_output : bool, optional
        Do not write output files.

        Args-only in library mode: no effect here -- write from the Result / Network
        (see the note under Parameters below).
    tree : bool, optional
        Write the modular hierarchy to a tree file. Enabled by default when no other
        output format is selected.

        Args-only in library mode: no effect here -- write from the Result / Network
        (see the note under Parameters below).
    ftree : bool, optional
        Write the modular hierarchy and aggregated links between nested modules to an
        ftree file. Used by Network Navigator.

        Args-only in library mode: no effect here -- write from the Result / Network
        (see the note under Parameters below).
    clu : bool, optional
        Write top-level module ids for each node to a clu file.

        Args-only in library mode: no effect here -- write from the Result / Network
        (see the note under Parameters below).
    clu_level : int, optional
        With --clu or --output clu, write module ids at this depth from the root. Use -1
        for bottom-level modules. Valid range: >= -1. Engine default: 1.

        Args-only in library mode: no effect here -- write from the Result / Network
        (see the note under Parameters below).
    output : sequence of str, optional
        Write selected output formats as a comma-separated list without spaces, e.g. -o
        clu,tree,ftree. Options: clu, tree, ftree, newick, json, csv, network, states,
        flow.

        Args-only in library mode: no effect here -- write from the Result / Network
        (see the note under Parameters below).
    hide_bipartite_nodes : bool, optional
        Hide bipartite nodes in output by projecting the solution to primary nodes.

        Args-only on the Python library surface. It projects the secondary (type-B)
        bipartite nodes out of what result.write_tree/write_clu emit, leaving the
        in-memory result covering both node types. Set it via Options and write from the
        Result to use it.
    print_all_trials : bool, optional
        Write each trial to separate output files. Has effect only when --num-trials is
        greater than 1.

        Args-only in library mode: no effect here -- write from the Result / Network
        (see the note under Parameters below).
    no_overwrite : bool, optional
        Fail with an output error if any target output file already exists. By default
        existing files are replaced.

        Args-only in library mode: no effect here -- write from the Result / Network
        (see the note under Parameters below).
    print_config_fingerprint : bool, optional
        Print the canonical configuration fingerprint and exit.

        Not a Python library option; it leaves the surface in 3.0. A print-and-exit CLI
        diagnostic; run the infomap binary.
    timing_json : str, optional
        Write machine-readable run timing JSON to this path. Use - for stdout.
    summary_json : str, optional
        Write machine-readable final run summary JSON to this path. Use - for stdout.
    manifest_json : str, optional
        Write a machine-readable run manifest JSON to this path. Use - for stdout.
    memory_report : bool, optional
        Include peak RSS and best-effort bytes per node/link estimates in timing JSON.
        Requires --timing-json.
    trial_offset : int, optional
        Global index of the first trial this process runs; trial i uses seed = base_seed
        + (trial_offset + i). Default 0 (single-process behavior). Valid range: >= 0.
        Engine default: 0.
    trial_results : str, optional
        Write this shard's per-trial results (codelengths, seeds, best-tree reference,
        fingerprints) as JSON to this path, for deterministic merging of distributed
        shard runs into a final solution.
    no_final_output : bool, optional
        Skip writing this process's aggregate best result. Per-trial outputs and
        --trial-results are still written.
    verbosity_level : int, optional
        Verbosity level on the console. 1 keeps the default output level, 2 renders -vv
        and so on.

        Not a Python library option; it leaves the surface in 3.0. A DEBUG-enabled
        'infomap' logger (infomap.enable_log(logging.DEBUG)) raises engine verbosity;
        logger levels filter the records.
    silent : bool, optional
        Suppress console output. The Python API is already quiet by default; to see the
        engine log, use infomap.enable_log() rather than this flag. The command-line
        interface is unaffected.

        Not a Python library option; it leaves the surface in 3.0. The Python API is
        quiet by default; logging is the control. Attach handlers to
        logging.getLogger('infomap') (e.g. infomap.enable_log()) for the engine log.
    two_level : bool, optional
        Optimize a two-level partition instead of the default multi-level hierarchy.
    flow_model : str, optional
        Choose how Infomap derives flow from the input links. Options: undirected,
        directed, undirdir, outdirdir, rawdir, precomputed.
    directed : bool, optional
        Treat input links as directed. Shorthand for --flow-model directed.
    recorded_teleportation : bool, optional
        When teleportation is used to calculate flow, also record teleportation steps in
        the codelength.
    use_node_weights_as_flow : bool, optional
        Use node weights from the API or Pajek node records as normalized node flow.
    to_nodes : bool, optional
        Teleport to nodes instead of links. Uses uniform node weights unless node
        weights are provided.
    teleportation_probability : float, optional
        Set the probability of teleporting to a random node or link when calculating
        flow. Valid range: between 0.0 and 1.0 (inclusive).
    max_flow_iterations : int, optional
        Limit the power iteration used to calculate flow (directed and regularized flow
        models) to this many iterations. Valid range: >= 1.
    min_flow_iterations : int, optional
        Require at least this many power iterations before the flow calculation can
        converge, even if --flow-tolerance is already met. Valid range: >= 0.
    flow_tolerance : float, optional
        Convergence tolerance for the power iteration used to calculate flow. Iteration
        stops once the per-iteration change in flow drops to or below this value, after
        --min-flow-iterations have run. Valid range: >= 0.0.
    regularized : bool, optional
        Add a fully connected Bayesian prior network to reduce overfitting to missing
        links. Activates --recorded-teleportation.
    regularization_strength : float, optional
        Scale the relative strength of the Bayesian prior network used by --regularized.
        Valid range: >= 0.0.
    entropy_corrected : bool, optional
        Correct for negative entropy bias in small samples, especially solutions with
        many modules.
    entropy_correction_strength : float, optional
        Scale the default correction used by --entropy-corrected. Valid range: >= 0.0.
    markov_time : float, optional
        Scale link flow to change the cost of moving between modules. Higher values
        result in fewer modules. Valid range: >= 0.0.
    variable_markov_time : bool, optional
        Vary Markov time locally to reduce overpartitioning in sparse areas while
        keeping higher resolution in dense areas.
    variable_markov_damping : float, optional
        With --variable-markov-time, set damping between local effective degree (0) and
        local entropy (1). Valid range: between 0.0 and 1.0 (inclusive).
    variable_markov_min_scale : float, optional
        With --variable-markov-time, set the minimum local scale for zero-entropy nodes.
        Local Markov time is max scale divided by local scale.
    preferred_number_of_modules : int, optional
        Penalize solutions by how far their number of modules differs from this value.
        Valid range: >= 1.
    preferred_number_of_levels : int, optional
        Soft preference for the depth of the hierarchy. Steering to a shallower depth is
        reliable at a small codelength cost; deeper is best-effort, bounded by what the
        optimizer proposes. No-op with --two-level or strength 0. Valid range: >= 1.
    preferred_number_of_levels_strength : float, optional
        Scale the strength of --preferred-number-of-levels. 0 disables the preference;
        larger values increase the cost of deviating from the preferred depth. Valid
        range: >= 0.0.
    multilayer_relax_rate : float, optional
        Set the probability of relaxing from a state node to neighboring layers instead
        of staying in the current layer. Valid range: between 0.0 and 1.0 (inclusive).
    multilayer_relax_limit : int, optional
        Limit relaxation to this many neighboring layer ids in each direction. Use a
        negative value to allow relaxation to any layer.
    multilayer_relax_limit_up : int, optional
        Limit relaxation upward to this many higher neighboring layer ids. Use a
        negative value to allow relaxation to any higher layer.
    multilayer_relax_limit_down : int, optional
        Limit relaxation downward to this many lower neighboring layer ids. Use a
        negative value to allow relaxation to any lower layer.
    multilayer_relax_by_jsd : bool, optional
        Weight multilayer relaxation by out-link similarity measured with Jensen-Shannon
        divergence.
    multilayer_relax_to_self : bool, optional
        On relaxation, link a state node to its own physical node in the target layer
        instead of spreading to its out-neighbors. Builds a smaller state network with
        the same flow as the default.
    seed : int, optional
        Set the random number generator seed for reproducible results. Valid range: >=
        1.
    num_trials : int, optional
        Run this many independent trials and keep the best solution. Valid range: >= 1.
    core_loop_limit : int, optional
        Limit how many core loops try to move each node to the best module. Valid range:
        >= 1.
    core_level_limit : int, optional
        Limit how many times core loops are reapplied to the aggregated modular network
        to find larger structures. 0 means no limit. Valid range: >= 0. Engine default:
        0.
    tune_iteration_limit : int, optional
        Limit the main iterations in the two-level partition algorithm. 0 means no
        limit. Valid range: >= 0. Engine default: 0.
    core_loop_codelength_threshold : float, optional
        Require at least this codelength improvement to accept a new solution in a core
        loop. Valid range: >= 0.0.
    tune_iteration_relative_threshold : float, optional
        Require each tune iteration to improve codelength by this fraction of the
        initial two-level codelength. Valid range: >= 0.0.
    fast_hierarchical_solution : int, optional
        Find top modules fast. Use 2 to keep all fast levels and 3 to skip the recursive
        part.
    inner_parallelization : bool, optional
        Experimental: use batched parallel node moves for coarse optimization.
        Performance gains are workload-dependent, often require a relaxed
        core-loop-codelength-threshold and low tune-iteration-limit, and may produce a
        different partition than serial optimization.
    parallel_trials : bool, optional
        Run independent trials in parallel with OpenMP. --num-trials remains the total
        number of trials; the number of parallel workers follows the OpenMP thread count
        (e.g. OMP_NUM_THREADS), clamped to --num-trials. Peak memory scales with the
        worker count. Nested OpenMP and --inner-parallelization are disabled inside
        workers.
    converge : bool, optional
        Treat the trial count as a cap and stop early once the best codelength has
        plateaued (no meaningful improvement over several consecutive trials). Runs
        trials serially; cannot be combined with parallel trials or distributed
        sharding. With no explicit trial count, a default cap is used.
    num_threads : str or int, optional
        Effective thread budget: 'auto' (resolve from --num-threads >
        INFOMAP_NUM_THREADS > SLURM_CPUS_PER_TASK > OMP_NUM_THREADS > cpuset >
        hardware), or a positive integer. 1 forces fully serial. Governs the recursive
        partition, parallel trials, and inner parallelization.
    threads : str or int, optional
        Alias for --num-threads.

        Not a Python library option; it leaves the surface in 3.0. Use num_threads;
        threads is a redundant alias of the same engine option.
    prefer_modular_solution : bool, optional
        Prefer a modular solution even when one module gives a lower codelength.
    num_random_moves : int, optional
        Try this many random moves in each core loop to merge weakly connected nodes.
        Valid range: >= 0.
    max_degree_for_random_moves : int, optional
        Try random moves only for nodes with degree at most this value. Valid range: >=
        0.
    include_self_links : bool, optional
        Deprecated. Self-links are included by default; use no_self_links=True to
        exclude them.
    """

    # input
    include_self_links: bool | None = None
    skip_adjust_bipartite_flow: bool = False
    bipartite_teleportation: bool = False
    weight_threshold: float | None = None
    no_self_links: bool = False
    node_limit: int | None = None
    matchable_multilayer_ids: int | None = None
    cluster_data: str | None = None
    assign_to_neighbouring_module: bool = False
    meta_data: str | None = None
    meta_data_rate: float = 1.0
    meta_data_unweighted: bool = False
    no_infomap: bool = False
    # output
    out_name: str | None = None
    no_file_output: bool = False
    tree: bool = False
    ftree: bool = False
    clu: bool = False
    clu_level: int | None = None
    output: list[OutputFormat] | tuple[OutputFormat, ...] | None = None
    hide_bipartite_nodes: bool = False
    print_all_trials: bool = False
    no_overwrite: bool = False
    print_config_fingerprint: bool = False
    timing_json: str | None = None
    summary_json: str | None = None
    manifest_json: str | None = None
    memory_report: bool = False
    trial_offset: int | None = None
    trial_results: str | None = None
    no_final_output: bool = False
    verbosity_level: int = 1
    silent: bool = True
    # algorithm
    two_level: bool = False
    flow_model: FlowModel | None = None
    directed: bool | None = None
    recorded_teleportation: bool = False
    use_node_weights_as_flow: bool = False
    to_nodes: bool = False
    teleportation_probability: float = 0.15
    max_flow_iterations: int = 400
    min_flow_iterations: int = 50
    flow_tolerance: float = 1e-15
    regularized: bool = False
    regularization_strength: float = 1.0
    entropy_corrected: bool = False
    entropy_correction_strength: float = 1.0
    markov_time: float = 1.0
    variable_markov_time: bool = False
    variable_markov_damping: float = 1.0
    variable_markov_min_scale: float = 1.0
    preferred_number_of_modules: int | None = None
    preferred_number_of_levels: int | None = None
    preferred_number_of_levels_strength: float = 1.0
    multilayer_relax_rate: float = 0.15
    multilayer_relax_limit: int = -1
    multilayer_relax_limit_up: int = -1
    multilayer_relax_limit_down: int = -1
    multilayer_relax_by_jsd: bool = False
    multilayer_relax_to_self: bool = False
    # accuracy
    seed: int = 123
    num_trials: int = 1
    core_loop_limit: int = 10
    core_level_limit: int | None = None
    tune_iteration_limit: int | None = None
    core_loop_codelength_threshold: float = 1e-10
    tune_iteration_relative_threshold: float = 1e-05
    fast_hierarchical_solution: int | None = None
    inner_parallelization: bool = False
    parallel_trials: bool = False
    converge: bool = False
    num_threads: str | int | None = None
    threads: str | int | None = None
    prefer_modular_solution: bool = False
    num_random_moves: int = 5
    max_degree_for_random_moves: int = 2

    def __post_init__(self):
        # Validate at construction so a bad value fails where it is
        # written, not later at the to_args() render funnel. to_args()
        # revalidates the merged result, so overrides are covered too.
        options = self.to_kwargs()
        _validate_option_domains(options)
        _validate_option_choices(options)

    @classmethod
    def _from_locals(cls, mapping):
        # Internal: build from a locals() dict, dropping the non-field
        # entries (self/args/cls). Public construction is the dataclass
        # constructor, Options(**mapping), which rejects unknown keys.
        return cls(**{name: mapping[name] for name in _OPTION_FIELD_NAMES if name in mapping})

    def to_kwargs(self):
        """Return the options as a keyword-argument dict.

        Returns
        -------
        dict
            A dict with one entry per option field, suitable for
            ``Infomap(**options.to_kwargs())``.
        """
        return {name: getattr(self, name) for name in _OPTION_FIELD_NAMES}

    def to_args(self, base_args: str | None = None):
        """Render the options as an Infomap command-line argument string.

        Options that keep their default values render no flags.

        Parameters
        ----------
        base_args : str, optional
            Raw Infomap arguments to prepend before the rendered flags.

        Returns
        -------
        str
            The rendered argument string, prefixed by ``base_args`` if
            given.
        """
        options = self.to_kwargs()
        _validate_option_domains(options)
        _validate_option_choices(options)
        if self.directed is not None and self.flow_model is not None:
            warnings.warn(
                f"both 'directed' and 'flow_model' are set; 'directed' "
                f"takes precedence and flow_model={self.flow_model!r} is "
                "ignored by the engine. Set only one (directed=True is shorthand for flow_model='directed').",
                UserWarning,
                stacklevel=_external_stacklevel(),
            )
        rendered_args = []

        if self.include_self_links is not None:
            warnings.warn(
                "include_self_links is deprecated, use no_self_links to exclude self-links",
                DeprecationWarning,
                stacklevel=_external_stacklevel(),
            )

        _append_option_specs(rendered_args, options, _INPUT_OPTION_SPECS)

        if (self.include_self_links is not None and not self.include_self_links) or self.no_self_links:
            rendered_args.append("--no-self-links")

        _append_option_specs(rendered_args, options, _OUTPUT_OPTION_SPECS)

        if self.verbosity_level > 1:
            rendered_args.append(f"-{'v' * self.verbosity_level}")

        if self.output is not None:
            rendered_args.append(f"--output {','.join(self.output)}")

        _append_option_specs(rendered_args, options, _ALGORITHM_OPTION_SPECS)

        if self.directed is not None:
            rendered_args.append("--directed" if self.directed else "--flow-model undirected")

        _append_option_specs(rendered_args, options, _ACCURACY_OPTION_SPECS)

        if self.fast_hierarchical_solution is not None:
            if self.fast_hierarchical_solution not in (1, 2, 3):
                raise ValueError(
                    "fast_hierarchical_solution="
                    f"{self.fast_hierarchical_solution!r} is not valid: use "
                    "1 (find top modules fast), 2 (keep all fast levels), "
                    "or 3 (skip the recursive part), or None to disable."
                )
            rendered_args.append(f"-{'F' * self.fast_hierarchical_solution}")

        return _join_args(base_args, rendered_args)


_OPTION_FIELD_NAMES = tuple(field.name for field in fields(Options))


# Options is the canonical public name; InfomapOptions stays as a back-compat alias.
InfomapOptions = Options


_OPTION_DEFAULTS = Options()
# The only facade keyword whose Infomap.run() default differs from
# Infomap.__init__(): run() defaults silent to False. A keyword left at its
# run-context default must defer to the options= carrier rather than
# spuriously override it.
_RUN_DEFAULT_OVERRIDES = {"silent": False}


def _context_default(name, context):
    if context == "run" and name in _RUN_DEFAULT_OVERRIDES:
        return _RUN_DEFAULT_OVERRIDES[name]
    return getattr(_OPTION_DEFAULTS, name)


def _merge_options(base, keyword_options, context):
    """Merge the ``options=`` carrier with the facade keyword options.

    ``base`` is the ``options=`` argument to ``Infomap()`` / ``Infomap.run()``
    (an :class:`Options`, a mapping, or ``None``); ``keyword_options`` is the
    :class:`Options` built from the facade's per-keyword parameters. A keyword
    left at its (context-appropriate) default defers to ``base``; a keyword
    set to a non-default value is an explicit override and wins -- mirroring
    the "overrides win over options" rule of :func:`infomap.run`.
    """
    if base is None:
        return keyword_options
    if isinstance(base, Mapping):
        base = Options(**base)
    elif not isinstance(base, Options):
        raise TypeError(
            "options must be an Options instance, a mapping, or None"
        )
    overrides = {
        name: getattr(keyword_options, name)
        for name in _OPTION_FIELD_NAMES
        if getattr(keyword_options, name) != _context_default(name, context)
    }
    return replace(base, **overrides)


def _construct_args(
    args=None,
    # input
    include_self_links=None,
    skip_adjust_bipartite_flow=False,
    bipartite_teleportation=False,
    weight_threshold=None,
    no_self_links=False,
    node_limit=None,
    matchable_multilayer_ids=None,
    cluster_data=None,
    assign_to_neighbouring_module=False,
    meta_data=None,
    meta_data_rate=1.0,
    meta_data_unweighted=False,
    no_infomap=False,
    # output
    out_name=None,
    no_file_output=False,
    tree=False,
    ftree=False,
    clu=False,
    clu_level=None,
    output=None,
    hide_bipartite_nodes=False,
    print_all_trials=False,
    no_overwrite=False,
    print_config_fingerprint=False,
    timing_json=None,
    summary_json=None,
    manifest_json=None,
    memory_report=False,
    trial_offset=None,
    trial_results=None,
    no_final_output=False,
    verbosity_level=1,
    silent=True,
    # algorithm
    two_level=False,
    flow_model=None,
    directed=None,
    recorded_teleportation=False,
    use_node_weights_as_flow=False,
    to_nodes=False,
    teleportation_probability=0.15,
    max_flow_iterations=400,
    min_flow_iterations=50,
    flow_tolerance=1e-15,
    regularized=False,
    regularization_strength=1.0,
    entropy_corrected=False,
    entropy_correction_strength=1.0,
    markov_time=1.0,
    variable_markov_time=False,
    variable_markov_damping=1.0,
    variable_markov_min_scale=1.0,
    preferred_number_of_modules=None,
    preferred_number_of_levels=None,
    preferred_number_of_levels_strength=1.0,
    multilayer_relax_rate=0.15,
    multilayer_relax_limit=-1,
    multilayer_relax_limit_up=-1,
    multilayer_relax_limit_down=-1,
    multilayer_relax_by_jsd=False,
    multilayer_relax_to_self=False,
    # accuracy
    seed=123,
    num_trials=1,
    core_loop_limit=10,
    core_level_limit=None,
    tune_iteration_limit=None,
    core_loop_codelength_threshold=1e-10,
    tune_iteration_relative_threshold=1e-05,
    fast_hierarchical_solution=None,
    inner_parallelization=False,
    parallel_trials=False,
    converge=False,
    num_threads=None,
    threads=None,
    prefer_modular_solution=False,
    num_random_moves=5,
    max_degree_for_random_moves=2,
):
    return Options._from_locals(locals()).to_args(base_args=args)
