from __future__ import annotations

import warnings
from dataclasses import dataclass, fields


# Generated by scripts/generate_binding_options.py from ./Infomap --print-json-parameters.
# Edit src/io/Config.cpp or interfaces/parameters/overrides.json, then run
# make build-binding-options.

_DEFAULT_META_DATA_RATE = 1.0
_DEFAULT_VERBOSITY_LEVEL = 1
_DEFAULT_TELEPORTATION_PROB = 0.15
_DEFAULT_MULTILAYER_RELAX_RATE = 0.15
_DEFAULT_SEED = 123
_DEFAULT_CORE_LOOP_CODELENGTH_THRESHOLD = 1e-10
_DEFAULT_TUNE_ITER_RELATIVE_THRESHOLD = 1e-5


_INPUT_OPTION_SPECS = (
    ("flag", "skip_adjust_bipartite_flow", "--skip-adjust-bipartite-flow", None),
    ("flag", "bipartite_teleportation", "--bipartite-teleportation", None),
    ("value", "weight_threshold", "--weight-threshold", lambda value: value is not None),
    ("value", "node_limit", "--node-limit", lambda value: value is not None),
    ("value", "matchable_multilayer_ids", "--matchable-multilayer-ids", lambda value: value is not None),
    ("value", "cluster_data", "--cluster-data", lambda value: value is not None),
    ("flag", "assign_to_neighbouring_module", "--assign-to-neighbouring-module", None),
    ("value", "meta_data", "--meta-data", lambda value: value is not None),
    ("value", "meta_data_rate", "--meta-data-rate", lambda value: value != 1.0),
    ("flag", "meta_data_unweighted", "--meta-data-unweighted", None),
    ("flag", "no_infomap", "--no-infomap", None),
)

_OUTPUT_OPTION_SPECS = (
    ("value", "out_name", "--out-name", lambda value: value is not None),
    ("flag", "no_file_output", "--no-file-output", None),
    ("flag", "tree", "--tree", None),
    ("flag", "ftree", "--ftree", None),
    ("flag", "clu", "--clu", None),
    ("value", "clu_level", "--clu-level", lambda value: value is not None),
    ("flag", "hide_bipartite_nodes", "--hide-bipartite-nodes", None),
    ("flag", "print_all_trials", "--print-all-trials", None),
    ("flag", "silent", "--silent", None),
)

_ALGORITHM_OPTION_SPECS = (
    ("flag", "two_level", "--two-level", None),
    ("value", "flow_model", "--flow-model", lambda value: value is not None),
    ("flag", "recorded_teleportation", "--recorded-teleportation", None),
    ("flag", "use_node_weights_as_flow", "--use-node-weights-as-flow", None),
    ("flag", "to_nodes", "--to-nodes", None),
    ("value", "teleportation_probability", "--teleportation-probability", lambda value: value != 0.15),
    ("flag", "regularized", "--regularized", None),
    ("value", "regularization_strength", "--regularization-strength", lambda value: value != 1.0),
    ("flag", "entropy_corrected", "--entropy-corrected", None),
    ("value", "entropy_correction_strength", "--entropy-correction-strength", lambda value: value != 1.0),
    ("value", "markov_time", "--markov-time", lambda value: value != 1.0),
    ("flag", "variable_markov_time", "--variable-markov-time", None),
    ("value", "variable_markov_damping", "--variable-markov-damping", lambda value: value != 1.0),
    ("value", "variable_markov_min_scale", "--variable-markov-min-scale", lambda value: value != 1.0),
    ("value", "preferred_number_of_modules", "--preferred-number-of-modules", lambda value: value is not None),
    ("value", "multilayer_relax_rate", "--multilayer-relax-rate", lambda value: value != 0.15),
    ("value", "multilayer_relax_limit", "--multilayer-relax-limit", lambda value: value != -1),
    ("value", "multilayer_relax_limit_up", "--multilayer-relax-limit-up", lambda value: value != -1),
    ("value", "multilayer_relax_limit_down", "--multilayer-relax-limit-down", lambda value: value != -1),
    ("flag", "multilayer_relax_by_jsd", "--multilayer-relax-by-jsd", None),
)

_ACCURACY_OPTION_SPECS = (
    ("value", "seed", "--seed", lambda value: value != 123),
    ("value", "num_trials", "--num-trials", lambda value: value != 1),
    ("value", "core_loop_limit", "--core-loop-limit", lambda value: value != 10),
    ("value", "core_level_limit", "--core-level-limit", lambda value: value is not None),
    ("value", "tune_iteration_limit", "--tune-iteration-limit", lambda value: value is not None),
    ("value", "core_loop_codelength_threshold", "--core-loop-codelength-threshold", lambda value: value != 1e-10),
    ("value", "tune_iteration_relative_threshold", "--tune-iteration-relative-threshold", lambda value: value != 1e-5),
    ("flag", "inner_parallelization", "--inner-parallelization", None),
    ("flag", "prefer_modular_solution", "--prefer-modular-solution", None),
    ("value", "num_random_moves", "--num-random-moves", lambda value: value is not None),
    ("value", "max_degree_for_random_moves", "--max-degree-for-random-moves", lambda value: value is not None),
    ("flag", "solution_landscape_tracking", "--solution-landscape-tracking", None),
    ("value", "solution_landscape_stop_after", "--solution-landscape-stop-after", lambda value: value is not None),
)


def _append_option_specs(parts, options, specs):
    for option_type, option_name, flag, include in specs:
        value = options[option_name]
        if option_type == "flag":
            if value:
                parts.append(flag)
            continue
        if include(value):
            parts.append(f"{flag} {value}")


def _join_args(base_args, parts):
    if not parts:
        return "" if base_args is None else base_args
    if not base_args:
        return f" {' '.join(parts)}"
    return f"{base_args} {' '.join(parts)}"


@dataclass(slots=True)
class InfomapOptions:
    """Reusable Infomap keyword options.

    This class mirrors the keyword arguments accepted by :class:`infomap.Infomap`
    and :meth:`infomap.Infomap.run`. Use :meth:`to_args` to render command-line
    flags, :meth:`from_mapping` to construct options from existing keyword
    dicts, or the convenience methods :meth:`infomap.Infomap.from_options` and
    :meth:`infomap.Infomap.run_with_options` to apply a reusable configuration.

    Parameters
    ----------
    skip_adjust_bipartite_flow : bool, optional
        Skip distributing all flow from the bipartite nodes to the primary nodes.
    bipartite_teleportation : bool, optional
        Teleport like the bipartite flow instead of two-step (unipartite) teleportation.
    weight_threshold : float, optional
        Limit the number of links to read from the network. Ignore links with less
        weight than the threshold.
    no_self_links : bool, optional
        Exclude self links in the input network.
    node_limit : int, optional
        Limit the number of nodes to read from the network. Ignore links connected to
        ignored nodes.
    matchable_multilayer_ids : int, optional
        Construct state ids from node and layer ids that are consistent across networks
        for the same max number of layers. Set to at least the largest layer id among
        networks to match.
    cluster_data : str, optional
        Provide an initial two-level (clu format) or multi-layer (tree format) solution.
    assign_to_neighbouring_module : bool, optional
        Assign nodes without module assignments (from --cluster-data) to the module
        assignment of a neighbouring node if possible.
    meta_data : str, optional
        Provide meta data (clu format) that should be encoded.
    meta_data_rate : float, optional
        Metadata encoding rate. Default is to encode each step.
    meta_data_unweighted : bool, optional
        Don't weight meta data by node flow.
    no_infomap : bool, optional
        Don't run the optimizer. Useful to calculate codelength of provided cluster data
        or to print non-modular statistics.
    out_name : str, optional
        Name for the output files, e.g. [output_directory]/[out-name].tree
    no_file_output : bool, optional
        Don't write output to file.
    tree : bool, optional
        Write a tree file with the modular hierarchy. Automatically enabled if no other
        output is specified.
    ftree : bool, optional
        Write a ftree file with the modular hierarchy including aggregated links between
        (nested) modules. (Used by Network Navigator)
    clu : bool, optional
        Write a clu file with the top cluster ids for each node.
    clu_level : int, optional
        For clu output, print modules at specified depth from root. Use -1 for bottom
        level modules.
    output : sequence of str, optional
        Comma-separated output formats without spaces, e.g. -o clu,tree,ftree. Options:
        clu, tree, ftree, newick, json, csv, network, states, flow.
    hide_bipartite_nodes : bool, optional
        Project bipartite solution to unipartite.
    print_all_trials : bool, optional
        Print all trials to separate files.
    verbosity_level : int, optional
        Verbosity level on the console. 1 keeps the default output level, 2 renders -vv
        and so on.
    silent : bool, optional
        No output on the console.
    two_level : bool, optional
        Optimize a two-level partition of the network. Default is multi-level.
    flow_model : str, optional
        Specify flow model. Options: undirected, directed, undirdir, outdirdir, rawdir,
        precomputed.
    directed : bool, optional
        Assume directed links. Shorthand for '--flow-model directed'.
    recorded_teleportation : bool, optional
        If teleportation is used to calculate the flow, also record it when minimizing
        codelength.
    use_node_weights_as_flow : bool, optional
        Use node weights (from api or after names in Pajek format) as flow, normalized
        to sum to 1
    to_nodes : bool, optional
        Teleport to nodes instead of to links, assuming uniform node weights if no such
        input data.
    teleportation_probability : float, optional
        Probability of teleporting to a random node or link.
    regularized : bool, optional
        Effectively add a fully connected Bayesian prior network to not overfit due to
        missing links. Implies recorded teleportation
    regularization_strength : float, optional
        Adjust relative strength of Bayesian prior network with this multiplier.
    entropy_corrected : bool, optional
        Correct for negative entropy bias in small samples (many modules).
    entropy_correction_strength : float, optional
        Increase or decrease the default entropy correction with this factor.
    markov_time : float, optional
        Scale link flow to change the cost of moving between modules. Higher values
        results in fewer modules.
    variable_markov_time : bool, optional
        Increase Markov time locally to level out link flow. Reduces risk of
        overpartitioning sparse areas while keeping high resolution in dense areas.
    variable_markov_damping : float, optional
        Damping parameter for variable Markov time, to scale with local effective degree
        (0) or local entropy (1).
    variable_markov_min_scale : float, optional
        Minimum local scale for nodes with zero entropy to avoid division by zero. Local
        Markov time is max scale divided by local scale.
    preferred_number_of_modules : int, optional
        Penalize solutions the more they differ from this number.
    multilayer_relax_rate : float, optional
        Probability to relax the constraint to move only in the current layer.
    multilayer_relax_limit : int, optional
        Number of neighboring layers in each direction to relax to. If negative, relax
        to any layer.
    multilayer_relax_limit_up : int, optional
        Number of neighboring layers with higher id to relax to. If negative, relax to
        any layer.
    multilayer_relax_limit_down : int, optional
        Number of neighboring layers with lower id to relax to. If negative, relax to
        any layer.
    multilayer_relax_by_jsd : bool, optional
        Relax proportional to the out-link similarity measured by the Jensen-Shannon
        divergence.
    seed : int, optional
        A seed (integer) to the random number generator for reproducible results.
    num_trials : int, optional
        Number of outer-most loops to run before picking the best solution.
    core_loop_limit : int, optional
        Limit the number of loops that tries to move each node into the best possible
        module.
    core_level_limit : int, optional
        Limit the number of times the core loops are reapplied on existing modular
        network to search bigger structures.
    tune_iteration_limit : int, optional
        Limit the number of main iterations in the two-level partition algorithm. 0
        means no limit.
    core_loop_codelength_threshold : float, optional
        Minimum codelength threshold for accepting a new solution in core loop.
    tune_iteration_relative_threshold : float, optional
        Set codelength improvement threshold of each new tune iteration to 'f' times the
        initial two-level codelength.
    fast_hierarchical_solution : int, optional
        Find top modules fast. Use 2 to keep all fast levels and 3 to skip the recursive
        part.
    inner_parallelization : bool, optional
        Parallelize the inner-most loop for greater speed. This may give some accuracy
        tradeoff.
    prefer_modular_solution : bool, optional
        Prefer modular solutions even if they are worse than putting all nodes in one
        module.
    num_random_moves : int, optional
        Number of random moves to try in core loop to try merge weakly connected nodes.
    max_degree_for_random_moves : int, optional
        Maximum degree of nodes for which to try random moves.
    solution_landscape_tracking : bool, optional
        Experimentally track final solution fingerprints across trials.
    solution_landscape_stop_after : int, optional
        Stop early after this many consecutive trials revisit known solution-landscape
        solutions. Requires --solution-landscape-tracking.
    include_self_links : bool, optional
        Deprecated. Self-links are included by default; use no_self_links=True to
        exclude them.
    """

    # input
    include_self_links: bool | None = None
    skip_adjust_bipartite_flow: bool = False
    bipartite_teleportation: bool = False
    weight_threshold: float | None = None
    no_self_links: bool = False
    node_limit: int | None = None
    matchable_multilayer_ids: int | None = None
    cluster_data: str | None = None
    assign_to_neighbouring_module: bool = False
    meta_data: str | None = None
    meta_data_rate: float = _DEFAULT_META_DATA_RATE
    meta_data_unweighted: bool = False
    no_infomap: bool = False
    # output
    out_name: str | None = None
    no_file_output: bool = False
    tree: bool = False
    ftree: bool = False
    clu: bool = False
    clu_level: int | None = None
    output: list[str] | tuple[str, ...] | None = None
    hide_bipartite_nodes: bool = False
    print_all_trials: bool = False
    verbosity_level: int = _DEFAULT_VERBOSITY_LEVEL
    silent: bool = False
    # algorithm
    two_level: bool = False
    flow_model: str | None = None
    directed: bool | None = None
    recorded_teleportation: bool = False
    use_node_weights_as_flow: bool = False
    to_nodes: bool = False
    teleportation_probability: float = _DEFAULT_TELEPORTATION_PROB
    regularized: bool = False
    regularization_strength: float = 1.0
    entropy_corrected: bool = False
    entropy_correction_strength: float = 1.0
    markov_time: float = 1.0
    variable_markov_time: bool = False
    variable_markov_damping: float = 1.0
    variable_markov_min_scale: float = 1.0
    preferred_number_of_modules: int | None = None
    multilayer_relax_rate: float = _DEFAULT_MULTILAYER_RELAX_RATE
    multilayer_relax_limit: int = -1
    multilayer_relax_limit_up: int = -1
    multilayer_relax_limit_down: int = -1
    multilayer_relax_by_jsd: bool = False
    # accuracy
    seed: int = _DEFAULT_SEED
    num_trials: int = 1
    core_loop_limit: int = 10
    core_level_limit: int | None = None
    tune_iteration_limit: int | None = None
    core_loop_codelength_threshold: float = _DEFAULT_CORE_LOOP_CODELENGTH_THRESHOLD
    tune_iteration_relative_threshold: float = _DEFAULT_TUNE_ITER_RELATIVE_THRESHOLD
    fast_hierarchical_solution: int | None = None
    inner_parallelization: bool = False
    prefer_modular_solution: bool = False
    num_random_moves: int | None = None
    max_degree_for_random_moves: int | None = None
    solution_landscape_tracking: bool = False
    solution_landscape_stop_after: int | None = None

    @classmethod
    def from_mapping(cls, mapping):
        return cls(**{name: mapping[name] for name in _OPTION_FIELD_NAMES if name in mapping})

    def to_kwargs(self):
        return {name: getattr(self, name) for name in _OPTION_FIELD_NAMES}

    def to_args(self, base_args: str | None = None):
        options = self.to_kwargs()
        rendered_args = []

        if self.include_self_links is not None:
            warnings.warn(
                "include_self_links is deprecated, use no_self_links to exclude self-links",
                DeprecationWarning,
                stacklevel=2,
            )

        _append_option_specs(rendered_args, options, _INPUT_OPTION_SPECS)

        if (self.include_self_links is not None and not self.include_self_links) or self.no_self_links:
            rendered_args.append("--no-self-links")

        _append_option_specs(rendered_args, options, _OUTPUT_OPTION_SPECS)

        if self.verbosity_level > 1:
            rendered_args.append(f"-{'v' * self.verbosity_level}")

        if self.output is not None:
            rendered_args.append(f"--output {','.join(self.output)}")

        _append_option_specs(rendered_args, options, _ALGORITHM_OPTION_SPECS)

        if self.directed is not None:
            rendered_args.append("--directed" if self.directed else "--flow-model undirected")

        _append_option_specs(rendered_args, options, _ACCURACY_OPTION_SPECS)

        if self.fast_hierarchical_solution is not None:
            rendered_args.append(f"-{'F' * self.fast_hierarchical_solution}")

        return _join_args(base_args, rendered_args)


_OPTION_FIELD_NAMES = tuple(field.name for field in fields(InfomapOptions))


def _construct_args(
    args=None,
    # input
    include_self_links=None,
    skip_adjust_bipartite_flow=False,
    bipartite_teleportation=False,
    weight_threshold=None,
    no_self_links=False,
    node_limit=None,
    matchable_multilayer_ids=None,
    cluster_data=None,
    assign_to_neighbouring_module=False,
    meta_data=None,
    meta_data_rate=_DEFAULT_META_DATA_RATE,
    meta_data_unweighted=False,
    no_infomap=False,
    # output
    out_name=None,
    no_file_output=False,
    tree=False,
    ftree=False,
    clu=False,
    clu_level=None,
    output=None,
    hide_bipartite_nodes=False,
    print_all_trials=False,
    verbosity_level=_DEFAULT_VERBOSITY_LEVEL,
    silent=False,
    # algorithm
    two_level=False,
    flow_model=None,
    directed=None,
    recorded_teleportation=False,
    use_node_weights_as_flow=False,
    to_nodes=False,
    teleportation_probability=_DEFAULT_TELEPORTATION_PROB,
    regularized=False,
    regularization_strength=1.0,
    entropy_corrected=False,
    entropy_correction_strength=1.0,
    markov_time=1.0,
    variable_markov_time=False,
    variable_markov_damping=1.0,
    variable_markov_min_scale=1.0,
    preferred_number_of_modules=None,
    multilayer_relax_rate=_DEFAULT_MULTILAYER_RELAX_RATE,
    multilayer_relax_limit=-1,
    multilayer_relax_limit_up=-1,
    multilayer_relax_limit_down=-1,
    multilayer_relax_by_jsd=False,
    # accuracy
    seed=_DEFAULT_SEED,
    num_trials=1,
    core_loop_limit=10,
    core_level_limit=None,
    tune_iteration_limit=None,
    core_loop_codelength_threshold=_DEFAULT_CORE_LOOP_CODELENGTH_THRESHOLD,
    tune_iteration_relative_threshold=_DEFAULT_TUNE_ITER_RELATIVE_THRESHOLD,
    fast_hierarchical_solution=None,
    inner_parallelization=False,
    prefer_modular_solution=False,
    num_random_moves=None,
    max_degree_for_random_moves=None,
    solution_landscape_tracking=False,
    solution_landscape_stop_after=None,
):
    return InfomapOptions.from_mapping(locals()).to_args(base_args=args)
