name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  native:
    uses: ./.github/workflows/_native-build.yml

  python:
    uses: ./.github/workflows/_python-package.yml
    with:
      run-tests: true
      build-release-artifacts: false

  javascript:
    uses: ./.github/workflows/_js-package.yml
    with:
      run-tests: true
      pack-artifact: false
